ALL: p0 p1 p2 p3
#Non-optimization
p0: newer_pav.cxx
	g++ newer_pav.cxx -O0 -o p0
#Optimum level 1
p1: newer_pav.cxx
	g++ newer_pav.cxx -O1 -o p1
#Optimum level 2
p2: newer_pav.cxx
	g++ newer_pav.cxx -O2 -o p2
#Optimum level 3
p3: newer_pav.cxx
	g++ newer_pav.cxx -O3 -o p3
