# A handy function to add the current source directory to a local
# filename. To be used for creating a list of sources.
function(convert_filenames_to_full_paths NAMES)
    unset(tmp_names)
    foreach(name ${${NAMES}})
        list(APPEND tmp_names ${CMAKE_CURRENT_SOURCE_DIR}/${name})
    endforeach()
    set(${NAMES} ${tmp_names} PARENT_SCOPE)
endfunction()


# Add executable examples in faspxx/example
macro(add_all_examples EXE_SRCS)
    set(EXE_PREFIX "")
    set(EXE_PREREQUISITE "")
    set(EXE_NEEDED_BY "")
    if (${ARGC} GREATER 1)
        set(EXE_PREFIX "${ARGV1}")
        if (${ARGC} GREATER 2)
            set(EXE_PREREQUISITE "${ARGV2}")
            if (${ARGC} GREATER 3)
                set(EXE_NEEDED_BY "${ARGV3}")
            endif()
        endif()
    endif()
    foreach(SRC_FILE IN LISTS ${EXE_SRCS})
        get_filename_component(SRC_FILENAME ${SRC_FILE} NAME)
        string(REPLACE ".cxx" "" EXE_NAME "${EXE_PREFIX}${SRC_FILENAME}")
        add_executable(${EXE_NAME} ${SRC_FILE})
        target_link_libraries(${EXE_NAME} faspxx)
    endforeach()
endmacro()