
ALL: p0 p1 p2 p3
#Non-optimization
p0: speedtest.cxx
	g++ speedtest.cxx -O0 -o p0
#Optimum level 1
p1: speedtest.cxx
	g++ speedtest.cxx -O1 -o p1
#Optimum level 2
p2: speedtest.cxx
	g++ speedtest.cxx -O2 -o p2
#Optimum level 3
p3: speedtest.cxx
	g++ speedtest.cxx -O3 -o p3
