FASP++: PCG Class Reference
PCG Class Reference
Preconditioned conjugate gradient method.
#include <PCG.hxx>
Public Member Functions
PCG ()
constructor by default
FaspRetCode Setup (const Mat &A)
check and allocate memory
FaspRetCode Solve (const VEC &b, VEC &x)
solve by PCG
~PCG ()
destructor
Public Member Functions inherited from SOL
SOL ()
Default constructor.
SOL (Output verbose, INT maxIter, DBL relTol, DBL absTol, INT restart)
constructor
void SetPrtLvl (Output verbose)
Set 'verbose' 's value.
void SetMaxIter (INT maxIter)
Set 'maxIter' 's value.
void SetRelTol (DBL relTol)
Set 'relTol' 's value.
void SetAbsTol (DBL absTol)
Set 'absTol' 's value.
void SetRestart (INT restart)
Set 'restart' 's value.
void SetSolver (SOLType solver)
Set 'solver' type.
DBL GetNorm2 ()
Get residual 's 'l2-norm'.
DBL GetInfNorm ()
Get residual 's 'infty-norm'.
INT GetIterations ()
Get iterations.
void Print (std::ostream &out=std::cout) const
Print parameters.
FaspRetCode SetOptionsFromFile (const char *file=nullptr, const char *prefix=nullptr)
Set 'verbose', 'maxIter', 'relTol', 'absTol', 'restart' 's values from file.
virtual void SetPC (SOL *pc)
build preconditioner operator
virtual void Clean ()
Release temporary memory.
~SOL ()
destructor
Additional Inherited Members
Protected Member Functions inherited from SOL
void RealRes (DBL relres)
Warning for actual relative residual.
void CompRes (DBL relres)
Warning for computed relative residual.
void DiffRes (DBL reldiff, DBL relres)
Output relative difference and residual.
void PrintInfo (const Output &verbose, const INT &iter, const DBL &resRel, const DBL &resAbs, const DBL &factor)
Print out iteration information for iterative solvers.
void PrintFinal (const Output &verbose, const INT &iter, const INT &maxit, const DBL &resRel)
Print out final status of an iterative method.
const char * SelectSolver (SOLType type)
Select solver.
Protected Attributes inherited from SOL
SOL * pc
Preconditioner, inlopfffpc.
const Mat * A
Matrix object.
Output verbose
Output level.
INT maxIter
Maximal number of iterations.
DBL relTol
Tolerance for relative residual.
DBL absTol
Tolerance for absolute residual.
INT restart
Tolerance for absolute residual.
SOLType type
Solver.
DBL norm2
l2-norm
DBL norminf
Infty-norm.
INT numIter
Iterations.
bool view
View all parameters.
bool mark
Mark where the PC is requesting memory.
Detailed Description
Preconditioned conjugate gradient method.
Member Function Documentation
Solve()
FaspRetCode PCG::Solve (const VEC & b, VEC & x) virtual
solve by PCG
Solve by PCG.
Reimplemented from SOL.
{
     // Check whether vector space sizes
     if (x.GetSize() != A->GetColSize() || b.GetSize() != A->GetRowSize() ||
         A->GetRowSize() != A->GetColSize())
         return FaspRetCode::ERROR_NONMATCH_SIZE;
     const unsigned MaxStag = 20; // Maximum number of stagnations
     const INT len = b.GetSize();
     const DBL maxdiff = 1e-4 * relTol; // Stagnation tolerance
     const DBL solinftol = 1e-20; // Infinity norm tolerance
     // Local variables
     FaspRetCode errorCode = FaspRetCode::SUCCESS;
     unsigned stagStep = 1, moreStep = 1;
     DBL resAbs = 1e+20, tmpAbs = 1e+20;
     DBL resRel = 1e+20, denAbs = 1e+20;
     DBL factor, alpha, beta, tmpa, tmpb;
     // Initial iteration
     numIter = 0;
     A->Apply(x, rk); // A * x -> rk
     rk.XPAY(-1.0, b); // b - rk -> rk
     pc->Solve(rk, zk); // B(r_k) -> z_k
     // Compute initial residual
     tmpAbs = rk.Norm2();
     denAbs = (1e-20 > tmpAbs) ? 1e-20 : tmpAbs;
     resRel = tmpAbs / denAbs;
     // If initial residual is already small, no need to iterate
     if (resRel < relTol || tmpAbs < absTol) goto FINISHED;
     // Prepare for the main loop
     PrintInfo(verbose, numIter, resRel, tmpAbs, 0.0);
     pk = zk;
     tmpa = zk.Dot(rk);
     // Main PCG loop
     while (numIter < maxIter) {
         numIter++; // iteration count
         A->Apply(pk, ax); // ax = A * p_k
         // alpha_k = (z_{k-1}, r_{k-1})/(A*p_{k-1},p_{k-1})
         tmpb = ax.Dot(pk);
         if (fabs(tmpb) > 1e-40) alpha = tmpa / tmpb;
         else {
             FASPXX_WARNING("Divided by zero!"); // Possible breakdown
             errorCode = FaspRetCode::ERROR_DIVIDE_ZERO;
             goto FINISHED;
         }
         x.AXPY(alpha, pk); // x_k = x_{k-1} + alpha_k*p_{k-1}
         rk.AXPY(-alpha, ax); // r_k = r_{k-1} - alpha_k*A*p_{k-1}
         // Compute norm of residual
         resAbs = rk.Norm2();
         resRel = resAbs / denAbs;
         factor = resAbs / tmpAbs;
         // Output iteration information if needed
         PrintInfo(verbose, numIter, resRel, tmpAbs, factor);
         if (factor > 0.9) // Only check when converge slowly
         {
             // Check I: if solution is close to zero, return ERROR_SOLVER_SOLSTAG
             DBL norminf = x.NormInf();
             if (norminf < solinftol) {
                 if (verbose > PRINT_MIN) FASPXX_WARNING(
                         "Iteration stopped -- solution almost zero!");
                 errorCode = FaspRetCode::ERROR_SOLVER_SOLSTAG;
                 break;
             }
             // Check II: if relative difference stagnated, try to restart
             DBL reldiff = fabs(alpha) * this->pk.Norm2() / x.Norm2();
             if ((stagStep <= MaxStag) && (reldiff < maxdiff)) {
                 if (verbose > PRINT_SOME) {
                     DiffRes(reldiff, resRel);
                     FASPXX_WARNING("Iteration restarted -- stagnation!");
                 }
                 A->Apply(x, this->rk);
                 this->rk.XPAY(-1.0, b);
                 resAbs = this->rk.Norm2();
                 resRel = resAbs / denAbs;
                 if (verbose > PRINT_SOME) RealRes(resRel);
                 if (resRel < relTol) break;
                 else {
                     if (stagStep >= MaxStag) {
                         if (verbose > PRINT_MIN) FASPXX_WARNING(
                                 "Iteration stopped -- stagnation!");
                         errorCode = FaspRetCode::ERROR_SOLVER_STAG;
                         break;
                     }
                     this->pk.SetValues(len, 0.0);
                     ++stagStep;
                 }
             } // End of stagnation check!
         } // End of check I and II
         // Check III: prevent false convergence
         if (resRel < relTol) {
             // Compute true residual r = b - Ax and update residual
             A->Apply(x, this->rk);
             this->rk.XPAY(-1.0, b);
             // Compute residual norms
             DBL updated_resRel = resRel;
             resAbs = rk.Norm2();
             resRel = resAbs / denAbs;
             // Check convergence
             if (resRel < relTol) break;
             if (verbose >= PRINT_MORE) {
                 CompRes(updated_resRel);
                 RealRes(resRel);
             }
             if (moreStep >= restart) {
                 if (verbose > PRINT_MIN) FASPXX_WARNING(
                         "The tolerence might be too small!");
                 errorCode = FaspRetCode::ERROR_SOLVER_TOLSMALL;
                 break;
             }
             // Prepare for restarting method
             this->pk.SetValues(len, 0.0);
             ++moreStep;
         } // End of safe-guard check!
         // Save residual for next iteration
         tmpAbs = resAbs;
         // Apply preconditioner z_k = B(r_k)
         pc->Solve(rk, zk);
         // Compute beta_k = (z_k, r_k)/(z_{k-1}, r_{k-1})
         tmpb = zk.Dot(rk);
         beta = tmpb / tmpa;
         tmpa = tmpb;
         // Compute p_k = z_k + beta_k*p_{k-1}
         pk.XPAY(beta, zk);
     } // End of main PCG loop
     FINISHED: // Finish iterative method
     PrintFinal(verbose, numIter, maxIter, resRel);
     // Compute final residual norms
     this->norminf = rk.NormInf();
     this->norm2 = rk.Norm2();
     return errorCode;
 }
References SOL::A, SOL::absTol, LOP::Apply(), VEC::AXPY(), VEC::Dot(), ERROR_DIVIDE_ZERO, ERROR_NONMATCH_SIZE, FASPXX_WARNING, LOP::GetColSize(), LOP::GetRowSize(), VEC::GetSize(), SOL::maxIter, VEC::Norm2(), SOL::norminf, VEC::NormInf(), SOL::numIter, SOL::pc, SOL::PrintInfo(), SOL::relTol, SOL::Solve(), SUCCESS, SOL::verbose, and VEC::XPAY().
The documentation for this class was generated from the following files:
PCG.hxx
PCG.cxx