FASP++: MAT Class Reference
MAT Class Reference
Sparse matrix class.
#include <MAT.hxx>
Public Member Functions
MAT ()
Default constructor.
MAT (const INT &nrow, const INT &mcol, const INT &nnz, const std::vector< DBL > &values, const std::vector< INT > &colInd, const std::vector< INT > &rowPtr, const std::vector< INT > &diagPtr)
Construct sparse matrix from a CSRx matrix.
MAT (const INT &nrow, const INT &mcol, const INT &nnz, const std::vector< DBL > &values, const std::vector< INT > &colInd, const std::vector< INT > &rowPtr)
Construct sparse matrix from a CSR matrix.
MAT (const INT &nrow, const INT &mcol, const INT &nnz, const std::vector< INT > &colInd, const std::vector< INT > &rowPtr)
Construct sparsity structure from a CSR matrix.
MAT (const INT &nrow, const INT &mcol, const INT &nnz, const std::vector< INT > &colInd, const std::vector< INT > &rowPtr, const std::vector< INT > &diagPtr)
Construct sparsity structure from a CSRx matrix.
MAT (const VEC &v)
Construct diagonal MAT matrix from a VEC object.
MAT (const std::vector< DBL > &v)
Construct diagonal MAT matrix from a vector object.
MAT (const MAT &mat)
Clone from another MAT.
~MAT ()=default
Default destructor.
MAT & operator= (const MAT &mat)
Overload = operator.
void SetValues (const INT &nrow, const INT &mcol, const INT &nnz, const std::vector< DBL > &values, const std::vector< INT > &colInd, const std::vector< INT > &rowPtr, const std::vector< INT > &diagPtr)
Set values of the matrix with CSRx format.
void SetValues (const INT &nrow, const INT &mcol, const INT &nnz, const std::vector< DBL > &values, const std::vector< INT > &colInd, const std::vector< INT > &rowPtr)
Set values of the matrix with CSR format.
INT GetNNZ () const
Get number of nonzeros of the matrix.
void GetDiag (VEC &v) const
Get the diagonal entries of *this and save them in a VEC object.
void GetDiagInv (MAT &m) const
Get reciprocal diagonal entries and save them in a MAT object.
void GetLowerTri (MAT &lTri) const
Get the lower triangular matrix.
void GetUpperTri (MAT &uTri) const
Get the upper triangular matrix.
void CopyTo (MAT &mat) const
Copy the matrix to another MAT object.
void Scale (const DBL a)
Scale the matrix with a scalar.
void Shift (const DBL a)
Shift the matrix with a scalar matrix.
void Zero ()
Set the matrix to a zero matrix.
void Apply (const VEC &v, VEC &w) const
Sparse matrix-vector multiplication.
void Transpose ()
Transpose of the matrix.
void MultTransposeAdd (const VEC &v1, const VEC &v2, VEC &v) const
Compute transpose of A multiply by v1 plus v2.
DBL GetValue (const INT &row, const INT &col) const
Get the value of [i,j]-entry of the matrix.
void Add (const DBL a, const MAT &mat1, const DBL b, const MAT &mat2)
*this = a * mat1 + b * mat2
void Mult (const MAT &matl, const MAT &matr)
*this = matl * matr
void MultLeft (const MAT &mat)
*this = *this * mat
void MultRight (const MAT &mat)
*this = mat * *this
Public Member Functions inherited from LOP
LOP ()
Default constructor.
LOP (const INT &nrow, const INT &mcol)
Make an LOP from VEC(mcol) to VEC(nrow).
LOP (const INT &nrow)
Make an LOP from VEC(nrow) to VEC(nrow).
LOP (const LOP &lop)
Make an LOP from another LOP.
LOP & operator= (const LOP &lop)
Overload the = operator.
~LOP ()=default
Default destructor.
INT GetRowSize () const
Get row space dimension.
INT GetColSize () const
Get column space dimension.
Friends
void WriteCSR (char *filename, MAT mat)
Write an MAT matrix to a disk file in CSR format.
void WriteMTX (char *filename, MAT mat)
Write an MAT matrix to a disk file in MTX format.
Additional Inherited Members
Protected Attributes inherited from LOP
INT nrow
number of rows
INT mcol
number of columns
Detailed Description
Sparse matrix class.
Constructor & Destructor Documentation
MAT() [1/7]
MAT::MAT (const INT & nrow, const INT & mcol, const INT & nnz, const std::vector< DBL > & values, const std::vector< INT > & colInd, const std::vector< INT > & rowPtr, const std::vector< INT > & diagPtr)
Construct sparse matrix from a CSRx matrix.
Assign nrow, mcol, nnz, values, colInd, rowPtr, diagPtr to *this.
{
     if (nrow == 0 || mcol == 0 || nnz == 0) {
         this->Empty();
         return;
     }
     this->nrow = nrow;
     this->mcol = mcol;
     this->nnz = nnz;
     this->values = values;
     this->colInd = colInd;
     this->rowPtr = rowPtr;
     this->diagPtr = diagPtr;
 }
References LOP::mcol, and LOP::nrow.
MAT() [2/7]
MAT::MAT (const INT & nrow, const INT & mcol, const INT & nnz, const std::vector< DBL > & values, const std::vector< INT > & colInd, const std::vector< INT > & rowPtr)
Construct sparse matrix from a CSR matrix.
Assign nrow, mcol, nnz, values, colInd, rowPtr to *this and generate diagPtr.
{
     if (nrow == 0 || mcol == 0 || nnz == 0) {
         this->Empty();
         return;
     }
     this->nrow = nrow;
     this->mcol = mcol;
     this->nnz = nnz;
     this->values = values;
     this->colInd = colInd;
     this->rowPtr = rowPtr;
     this->FormDiagPtr();
 }
References LOP::mcol, and LOP::nrow.
MAT() [3/7]
MAT::MAT (const INT & nrow, const INT & mcol, const INT & nnz, const std::vector< INT > & colInd, const std::vector< INT > & rowPtr)
Construct sparsity structure from a CSR matrix.
Assign nrow, mcol, nnz, colInd, rowPtr to *this and generate diagPtr.
{
     if (nrow == 0 || mcol == 0 || nnz == 0) {
         this->Empty();
         return;
     }
     this->nrow = nrow;
     this->mcol = mcol;
     this->nnz = nnz;
     this->colInd = colInd;
     this->rowPtr = rowPtr;
     this->values.resize(0);
     this->FormDiagPtr();
 }
References LOP::mcol, and LOP::nrow.
MAT() [4/7]
MAT::MAT (const INT & nrow, const INT & mcol, const INT & nnz, const std::vector< INT > & colInd, const std::vector< INT > & rowPtr, const std::vector< INT > & diagPtr)
Construct sparsity structure from a CSRx matrix.
Assign nrow, mcol, nnz, colInd, rowPtr, diagPtr to *this.
{
     if (nrow == 0 || mcol == 0 || nnz == 0) {
         this->Empty();
         return;
     }
     this->nrow = nrow;
     this->mcol = mcol;
     this->nnz = nnz;
     this->colInd = colInd;
     this->rowPtr = rowPtr;
     this->diagPtr = diagPtr;
     this->values.resize(0);
 }
References LOP::mcol, and LOP::nrow.
MAT() [5/7]
MAT::MAT (const VEC & v) explicit
Construct diagonal MAT matrix from a VEC object.
Assign diagonal values from a VEC to *this.
                      {
     INT size = v.GetSize();
     // Return an empty matrix if size==0
     if (size == 0) {
         this->Empty();
         return;
     }
     // Set MAT size
     this->nrow = size;
     this->mcol = size;
     this->nnz = size;
     INT *p;
     try {
         p = new INT[size + 1];
     } catch (std::bad_alloc &ex) {
         this->nrow = 0;
         this->mcol = 0;
         this->nnz = 0;
         throw( FaspBadAlloc(__FILE__, __FUNCTION__, __LINE__) );
     }
     // Set values from v
     this->values.resize(size);
     for (INT j = 0; j < size; ++j) this->values[j] = v.values[j];
     // Set colInd to {0, 1, ..., size-1}
     for (INT j = 0; j <= size; ++j) p[j] = j;
     this->colInd.resize(size);
     this->colInd.assign(p, p + size);
     // Set rowPtr to {0, 1, ..., size}
     this->rowPtr.resize(size + 1);
     this->rowPtr.assign(p, p + size + 1);
     // Set diagPtr to {0, 1, ..., size-1}
     this->diagPtr.resize(size);
     this->diagPtr.assign(p, p + size);
     delete[] p;
 }
References VEC::GetSize(), LOP::mcol, and LOP::nrow.
MAT() [6/7]
MAT::MAT (const std::vector< DBL > & v) explicit
Construct diagonal MAT matrix from a vector object.
Assign diagonal values from a vector to *this.
{
     const INT size = vt.size();
     // Return an empty matrix if size==0
     if (size == 0) {
         this->Empty();
         return;
     }
     // Set MAT size
     this->nrow = size;
     this->mcol = size;
     this->nnz = size;
     INT *p;
     try {
         p = new INT[size + 1];
     } catch (std::bad_alloc &ex) {
         this->nrow = 0;
         this->mcol = 0;
         this->nnz = 0;
         throw( FaspBadAlloc(__FILE__, __FUNCTION__, __LINE__) );
     }
     // Set values from vt
     this->values.resize(size);
     this->values.assign(vt.begin(), vt.begin() + size);
     // Set colInd to {0, 1, ..., size-1}
     for (INT j = 0; j <= size; ++j) p[j] = j;
     this->colInd.resize(size);
     this->colInd.assign(p, p + size);
     // Set rowPtr to {0, 1, ..., size}
     this->rowPtr.resize(size + 1);
     this->rowPtr.assign(p, p + size + 1);
     // Set diagPtr to {0, 1, ..., size-1}
     this->diagPtr.resize(size);
     this->diagPtr.assign(p, p + size);
     delete[] p;
 }
References LOP::mcol, and LOP::nrow.
MAT() [7/7]
MAT::MAT (const MAT & mat)
Clone from another MAT.
Assign MAT object to *this.
{
     this->nrow = mat.nrow;
     this->mcol = mat.mcol;
     this->nnz = mat.nnz;
     this->values = mat.values;
     this->colInd = mat.colInd;
     this->rowPtr = mat.rowPtr;
     this->diagPtr = mat.diagPtr;
 }
References LOP::mcol, and LOP::nrow.
Member Function Documentation
Add()
void MAT::Add (const DBL a, const MAT & mat1, const DBL b, const MAT & mat2)
*this = a * mat1 + b * mat2
*this = a * mat1 + b * mat2.
{
     MAT tmpMat;
     INT i, j, k, l;
     INT count = 0, added, countrow;
     if (mat1.nnz == 0) {
         tmpMat = mat2;
         tmpMat.Scale(b);
         return;
     }
     if (mat2.nnz == 0) {
         tmpMat = mat1;
         tmpMat.Scale(a);
         return;
     }
     tmpMat.nrow = mat1.nrow;
     tmpMat.mcol = mat1.mcol;
     tmpMat.rowPtr.resize(tmpMat.nrow + 1);
     tmpMat.colInd.resize(mat1.nnz + mat2.nnz);
     tmpMat.values.resize(mat1.nnz + mat2.nnz);
     tmpMat.colInd.assign(mat1.nnz + mat2.nnz, -1);
     for (i = 0; i < mat1.nrow; ++i) {
         countrow = 0;
         for (j = mat1.rowPtr[i]; j < mat1.rowPtr[i + 1]; ++j) {
             tmpMat.values[count] = a * mat1.values[j];
             tmpMat.colInd[count] = mat1.colInd[j];
             ++tmpMat.rowPtr[i + 1];
             ++count;
             ++countrow;
         }
         for (k = mat2.rowPtr[i]; k < mat2.rowPtr[i + 1]; ++k) {
             added = 0;
             for (l = tmpMat.rowPtr[i]; l < tmpMat.rowPtr[i] + countrow + 1; ++l) {
                 if (mat2.colInd[k] == tmpMat.colInd[l]) {
                     tmpMat.values[l] = tmpMat.values[l] + b * mat2.values[k];
                     added = 1;
                     break;
                 }
             }
             if (added == 0) {
                 tmpMat.values[count] = b * mat2.values[k];
                 tmpMat.colInd[count] = mat2.colInd[k];
                 ++tmpMat.rowPtr[i + 1];
                 ++count;
             }
         }
         tmpMat.rowPtr[i + 1] += tmpMat.rowPtr[i];
     }
     tmpMat.nnz = count;
     tmpMat.colInd.resize(count);
     tmpMat.values.resize(count);
     tmpMat.colInd.shrink_to_fit();
     tmpMat.values.shrink_to_fit();
     SortCSRRow(tmpMat.nrow, tmpMat.mcol, tmpMat.nnz, tmpMat.rowPtr, tmpMat.colInd,
                tmpMat.values);
     tmpMat.FormDiagPtr();
     *this = tmpMat;
 }
References LOP::mcol, LOP::nrow, Scale(), and SortCSRRow().
Apply()
void MAT::Apply (const VEC & v, VEC & w) const virtual
Sparse matrix-vector multiplication.
Compute w = *this * v.
Reimplemented from LOP.
{
     INT begin, i, k;
     if (this->values.size() > 0) { // Regular sparse matrix
         for (i = 0; i < this->nrow; ++i) {
             begin = this->rowPtr[i];
             switch (this->rowPtr[i + 1] - begin) {
                 case 4:
                     w.values[i] = this->values[begin]
                                   * v.values[this->colInd[begin]];
                     w.values[i] += this->values[begin + 1]
                                    * v.values[this->colInd[begin + 1]];
                     w.values[i] += this->values[begin + 2]
                                    * v.values[this->colInd[begin + 2]];
                     w.values[i] += this->values[begin + 3]
                                    * v.values[this->colInd[begin + 3]];
                     break;
                 case 5:
                     w.values[i] = this->values[begin]
                                   * v.values[this->colInd[begin]];
                     w.values[i] += this->values[begin + 1]
                                    * v.values[this->colInd[begin + 1]];
                     w.values[i] += this->values[begin + 2]
                                    * v.values[this->colInd[begin + 2]];
                     w.values[i] += this->values[begin + 3]
                                    * v.values[this->colInd[begin + 3]];
                     w.values[i] += this->values[begin + 4]
                                    * v.values[this->colInd[begin + 4]];
                     break;
                 case 6:
                     w.values[i] = this->values[begin]
                                   * v.values[this->colInd[begin]];
                     w.values[i] += this->values[begin + 1]
                                    * v.values[this->colInd[begin + 1]];
                     w.values[i] += this->values[begin + 2]
                                    * v.values[this->colInd[begin + 2]];
                     w.values[i] += this->values[begin + 3]
                                    * v.values[this->colInd[begin + 3]];
                     w.values[i] += this->values[begin + 4]
                                    * v.values[this->colInd[begin + 4]];
                     w.values[i] += this->values[begin + 5]
                                    * v.values[this->colInd[begin + 5]];
                     break;
                 default:
                     w.values[i] =
                             this->values[begin] * v.values[this->colInd[begin]];
                     for (k = begin + 1; k < this->rowPtr[i + 1]; ++k)
                         w.values[i] += this->values[k] * v.values[this->colInd[k]];
             }
         }
     } else { // Only sparse structure
         for (i = 0; i < this->nrow; ++i) {
             begin = this->rowPtr[i];
             switch (this->rowPtr[i + 1] - begin) {
                 case 4:
                     w.values[i] = v.values[this->colInd[begin]];
                     w.values[i] += v.values[this->colInd[begin + 1]];
                     w.values[i] += v.values[this->colInd[begin + 2]];
                     w.values[i] += v.values[this->colInd[begin + 3]];
                     break;
                 case 5:
                     w.values[i] = v.values[this->colInd[begin]];
                     w.values[i] += v.values[this->colInd[begin + 1]];
                     w.values[i] += v.values[this->colInd[begin + 2]];
                     w.values[i] += v.values[this->colInd[begin + 3]];
                     w.values[i] += v.values[this->colInd[begin + 4]];
                     break;
                 case 6:
                     w.values[i] = v.values[this->colInd[begin]];
                     w.values[i] += v.values[this->colInd[begin + 1]];
                     w.values[i] += v.values[this->colInd[begin + 2]];
                     w.values[i] += v.values[this->colInd[begin + 3]];
                     w.values[i] += v.values[this->colInd[begin + 4]];
                     w.values[i] += v.values[this->colInd[begin + 5]];
                     break;
                 default:
                     w.values[i] = v.values[this->colInd[begin]];
                     for (k = begin + 1; k < this->rowPtr[i + 1]; ++k)
                         w.values[i] += v.values[this->colInd[k]];
             }
         }
     } // end if values.size > 0
 }
References LOP::nrow.
CopyTo()
void MAT::CopyTo (MAT & mat) const
Copy the matrix to another MAT object.
Copy *this to mat.
{
     mat = *this;
 }
GetDiagInv()
void MAT::GetDiagInv (MAT & m) const
Get reciprocal diagonal entries and save them in a MAT object.
Get the diagonal entries 's reciprocal of *this and save them in a MAT object.
{
     m.nrow = this->nrow;
     m.mcol = this->mcol;
     m.nnz = this->nrow;
     m.rowPtr.resize(m.nrow + 1);
     for (INT j = 0; j < m.nrow + 1; ++j)
         m.rowPtr[j] = j;
     m.diagPtr.resize(m.nrow);
     for (INT j = 0; j < m.nrow; ++j)
         m.diagPtr[j] = j;
     m.colInd.resize(m.nnz);
     for (INT j = 0; j < m.nnz; ++j)
         m.colInd[j] = j;
     m.values.resize(m.nnz);
     for (INT j = 0; j < m.nnz; ++j)
         m.values[j] = 1.0 / this->values[this->diagPtr[j]];
 }
References LOP::mcol, and LOP::nrow.
GetNNZ()
INT MAT::GetNNZ () const
Get number of nonzeros of the matrix.
Return this->nnz.
                       {
     return this->nnz;
 }
GetValue()
DBL MAT::GetValue (const INT & irow, const INT & jcol) const
Get the value of [i,j]-entry of the matrix.
Get (*this)[i][j].
Note
If *this is a sparse structure, it will return 1.0 for nonzero entries.
{
     if ( this->colInd[this->rowPtr[irow]] <= jcol &&
          this->colInd[this->rowPtr[irow + 1] - 1] >= jcol ) {
         for ( INT j = this->rowPtr[irow]; j < this->rowPtr[irow + 1]; ++j ) {
             if ( jcol == this->colInd[j] ) {
                 if ( this->values.size() > 0 )
                     return this->values[j];
                 else
                     return 1.0; // sparse structure indicator
             }
         }
     }
     return 0.0;
 }
Mult()
void MAT::Mult (const MAT & matl, const MAT & matr)
*this = matl * matr
*this = matl * matr.
{
     INT l, count;
     INT *tmp = new INT[matr.mcol];
     MAT mat;
     this->nrow = matl.nrow;
     this->mcol = matr.mcol;
     this->rowPtr.resize(this->nrow + 1);
     for (INT i = 0; i < matr.mcol; ++i) tmp[i] = -1;
     for (INT i = 0; i < this->nrow; ++i) {
         count = 0;
         for (INT k = matl.rowPtr[i]; k < matl.rowPtr[i + 1]; ++k) {
             for (INT j = matr.rowPtr[matl.colInd[k]];
                  j < matr.rowPtr[matl.colInd[k] + 1]; ++j) {
                 for (l = 0; l < count; ++l) {
                     if (tmp[l] == matr.colInd[j]) break;
                 }
                 if (l == count) {
                     tmp[count] = matr.colInd[j];
                     ++count;
                 }
             }
         }
         this->rowPtr[i + 1] = count;
         for (INT j = 0; j < count; ++j) tmp[j] = -1;
     }
     for (INT i = 0; i < this->nrow; ++i) this->rowPtr[i + 1] += this->rowPtr[i];
     INT count_tmp;
     this->colInd.resize(this->rowPtr[this->nrow]);
     for (INT i = 0; i < this->nrow; ++i) {
         count_tmp = 0;
         count = this->rowPtr[i];
         for (INT k = matl.rowPtr[i]; k < matl.rowPtr[i + 1]; ++k) {
             for (INT j = matr.rowPtr[matl.colInd[k]];
                  j < matr.rowPtr[matl.colInd[k] + 1]; ++j) {
                 for (l = 0; l < count_tmp; ++l) {
                     if (tmp[l] == matr.colInd[j]) break;
                 }
                 if (l == count_tmp) {
                     this->colInd[count] = matr.colInd[j];
                     tmp[count_tmp] = matr.colInd[j];
                     ++count;
                     ++count_tmp;
                 }
             }
         }
         for (INT j = 0; j < count_tmp; ++j) tmp[j] = -1;
     }
     delete[] tmp;
     tmp = nullptr;
     this->values.resize(this->rowPtr[this->nrow]);
     for (INT i = 0; i < this->nrow; ++i) {
         for (INT j = this->rowPtr[i]; j < this->rowPtr[i + 1]; ++j) {
             this->values[j] = 0;
             for (INT k = matl.rowPtr[i]; k < matl.rowPtr[i + 1]; ++k) {
                 for (l = matr.rowPtr[matl.colInd[k]];
                      l < matr.rowPtr[matl.colInd[k] + 1]; ++l) {
                     if (matr.colInd[l] == this->colInd[j])
                         this->values[j] += matl.values[k] * matr.values[l];
                 }
             }
         }
     }
     this->nnz = this->rowPtr[this->nrow] - this->rowPtr[0];
     this->FormDiagPtr();
 }
References LOP::mcol, and LOP::nrow.
MultLeft()
void MAT::MultLeft (const MAT & mat)
*this = *this * mat
*this = *this * mat.
{
     MAT tmp;
     tmp = *this;
     Mult(tmp, mat);
 }
References Mult().
MultRight()
void MAT::MultRight (const MAT & mat)
*this = mat * *this
*this = mat * *this.
{
     MAT tmp;
     tmp = *this;
     Mult(mat, tmp);
 }
References Mult().
MultTransposeAdd()
void MAT::MultTransposeAdd (const VEC & v1, const VEC & v2, VEC & v) const
Compute transpose of A multiply by v1 plus v2.
Compute v = A'*v1 + v2.
{
     const INT n = this->nrow, m = this->mcol, nnz = this->nnz;
     INT i, j, k, p;
     MAT tmp;
     tmp.nrow = m;
     tmp.mcol = n;
     tmp.nnz = nnz;
     try {
         tmp.rowPtr.resize(m + 1);
         tmp.colInd.resize(nnz);
     } catch (std::bad_alloc &ex) {
         throw( FaspBadAlloc(__FILE__, __FUNCTION__, __LINE__) );
     }
     if (this->values.size()) {
         try {
             tmp.values.resize(nnz);
         } catch (std::bad_alloc &ex) {
             throw( FaspBadAlloc(__FILE__, __FUNCTION__, __LINE__) );
         }
     } else {
         tmp.values.resize(0);
     }
     for (j = 0; j < nnz; ++j) {
         i = this->colInd[j];
         if (i < m - 1) ++tmp.rowPtr[i + 2];
     }
     for (i = 2; i <= m; ++i) tmp.rowPtr[i] += tmp.rowPtr[i - 1];
     if (this->values.size()) {
         for (i = 0; i < n; ++i) {
             INT begin = this->rowPtr[i];
             for (p = begin; p < this->rowPtr[i + 1]; ++p) {
                 j = this->colInd[p] + 1;
                 k = tmp.rowPtr[j];
                 tmp.colInd[k] = i;
                 tmp.values[k] = this->values[p];
                 tmp.rowPtr[j] = k + 1;
             }
         }
     } else {
         for (i = 0; i < n; ++i) {
             INT begin = this->rowPtr[i];
             for (p = begin; p < this->rowPtr[i + 1]; ++p) {
                 j = this->colInd[p] + 1;
                 k = tmp.rowPtr[j];
                 tmp.colInd[k] = i;
                 tmp.rowPtr[j] = k + 1;
             }
         }
     }
     v = v2;
     INT begin;
     for (i = 0; i < tmp.nrow; ++i) {
         begin = tmp.rowPtr[i];
         for (j = begin; j < this->rowPtr[i + 1]; ++j)
             v.values[i] += v1.values[tmp.colInd[j]] * tmp.values[j];
     }
 }
References LOP::mcol, and LOP::nrow.
operator=()
MAT & MAT::operator= (const MAT & mat)
Overload = operator.
Assignment for the MAT object.
{
     this->nrow = mat.nrow;
     this->mcol = mat.mcol;
     this->nnz = mat.nnz;
     this->values = mat.values;
     this->colInd = mat.colInd;
     this->rowPtr = mat.rowPtr;
     this->diagPtr = mat.diagPtr;
     return *this;
 }
References LOP::mcol, and LOP::nrow.
Scale()
void MAT::Scale (const DBL a)
Scale the matrix with a scalar.
Scale *this *= a.
{
     if (this->values.empty()) return; // MAT is a sparse structure!!!
     for (INT j = 0; j < this->nnz; ++j) this->values[j] *= a;
 }
SetValues() [1/2]
void MAT::SetValues (const INT & nrow, const INT & mcol, const INT & nnz, const std::vector< DBL > & values, const std::vector< INT > & colInd, const std::vector< INT > & rowPtr)
Set values of the matrix with CSR format.
Set values of nrow, mcol, nnz, values, rowPtr, colInd.
{
     if (nrow == 0 || mcol == 0 || nnz == 0) {
         this->Empty();
         return;
     }
     this->nrow = nrow;
     this->mcol = mcol;
     this->nnz = nnz;
     this->rowPtr = rowPtr;
     this->colInd = colInd;
     this->values = values;
     this->FormDiagPtr();
 }
References LOP::mcol, and LOP::nrow.
SetValues() [2/2]
void MAT::SetValues (const INT & nrow, const INT & mcol, const INT & nnz, const std::vector< DBL > & values, const std::vector< INT > & colInd, const std::vector< INT > & rowPtr, const std::vector< INT > & diagPtr)
Set values of the matrix with CSRx format.
Set values of nrow, mcol, nnz, values, colInd, rowPtr, diagPtr.
{
     if (nrow == 0 || mcol == 0 || nnz == 0) {
         this->Empty();
         return;
     }
     this->nrow = nrow;
     this->mcol = mcol;
     this->nnz = nnz;
     this->values = values;
     this->rowPtr = rowPtr;
     this->colInd = colInd;
     this->diagPtr = diagPtr;
 }
References LOP::mcol, and LOP::nrow.
Shift()
void MAT::Shift (const DBL a)
Shift the matrix with a scalar matrix.
Shift *this += a * I.
{
     if (this->values.empty()) {
         return; // MAT is a sparse structure!!!
     }
     for (INT j = 0; j < this->diagPtr.size(); ++j)
         this->values[this->diagPtr[j]] += a;
 }
Transpose()
void MAT::Transpose ()
Transpose of the matrix.
Transpose *this in place.
                     {
     const INT n = this->nrow, m = this->mcol, nnz = this->nnz;
     INT i, j, k, p;
     MAT tmp;
     tmp.nrow = this->mcol;
     tmp.mcol = this->nrow;
     tmp.nnz = this->nnz;
     try {
         tmp.rowPtr.resize(this->mcol + 1);
         tmp.colInd.resize(nnz);
     } catch (std::bad_alloc &ex) {
         throw( FaspBadAlloc(__FILE__, __FUNCTION__, __LINE__) );
     }
     if (!this->values.empty()) {
         try {
             tmp.values.resize(nnz);
         } catch (std::bad_alloc &ex) {
             throw( FaspBadAlloc(__FILE__, __FUNCTION__, __LINE__) );
         }
     } else {
         tmp.values.resize(0);
     }
     for (INT j = 0; j < nnz; ++j) {
         i = this->colInd[j];
         if (i < m - 1) ++tmp.rowPtr[i + 2];
     }
     for (i = 2; i <= m; ++i) tmp.rowPtr[i] += tmp.rowPtr[i - 1];
     if (this->values.size()) {
         for (i = 0; i < n; ++i) {
             INT begin = this->rowPtr[i];
             for (p = begin; p < this->rowPtr[i + 1]; ++p) {
                 j = this->colInd[p] + 1;
                 k = tmp.rowPtr[j];
                 tmp.colInd[k] = i;
                 tmp.values[k] = this->values[p];
                 tmp.rowPtr[j] = k + 1;
             }
         }
     } else {
         for (i = 0; i < n; ++i) {
             INT begin = this->rowPtr[i];
             for (p = begin; p < this->rowPtr[i + 1]; ++p) {
                 j = this->colInd[p] + 1;
                 k = tmp.rowPtr[j];
                 tmp.colInd[k] = i;
                 tmp.rowPtr[j] = k + 1;
             }
         }
     }
     tmp.FormDiagPtr();
     this->operator=(tmp);
 }
References LOP::mcol, LOP::nrow, and operator=().
Zero()
void MAT::Zero ()
Set the matrix to a zero matrix.
Set all the entries to zero, without changing matrix size.
                {
     for (INT j = 0; j < this->nnz; ++j) values[j] = 0.0;
 }
The documentation for this class was generated from the following files:
MAT.hxx
MAT.cxx