FASP++: BiCGStab Class Reference
BiCGStab Class Reference
Preconditioned bi-conjugate gradient stabilized method.
#include <BiCGStab.hxx>
Public Member Functions
BiCGStab ()
Default constructor.
~BiCGStab ()=default
Default destructor.
FaspRetCode Setup (const LOP &A) override
Setup the BiCGStab method.
void Clean () override
Clean up CG data allocated during Setup.
FaspRetCode Solve (const VEC &b, VEC &x) override
Solve Ax=b using the BiCGStab method.
Public Member Functions inherited from SOL
SOL ()
Default constructor.
~SOL ()
Default destructor.
void SetOutput (Output verbose)
Set output level.
void SetMaxIter (int maxIter)
Set max number of iterations.
void SetMinIter (int minIter)
Set min number of iterations.
void SetSavIter (int savIter)
Set number of safe-guard iterations.
void SetRestart (int restart)
Set restart number for Krylov methods.
void SetRelTol (double relTol)
Set tolerance for relative residual.
void SetAbsTol (double absTol)
Set tolerance for absolute residual.
void SetSolType (SOLType solver)
Set solver type.
const char * GetSolType (SOLType type) const
Get solver type.
double GetNorm2 () const
Get Euclidean norm of residual.
double GetInfNorm () const
Get infinity norm of residual.
int GetIterations () const
Get number of iterations.
void PrintParam (std::ostream &out=std::cout) const
Print parameters.
void PrintHead (std::ostream &out=std::cout) const
Print out iteration information table header.
void PrintInfo (const int &iter, const double &resRel, const double &resAbs, const double &factor, std::ostream &out=std::cout) const
Print out iteration information for iterative solvers.
void PrintFinal (const int &iter, const double &resRel, const double &resAbs, const double &ratio, std::ostream &out=std::cout) const
Print out final status of an iterative method.
void PrintTime (const double duration, std::ostream &out=std::cout) const
Print out duration of solver.
virtual void SetupPCD (SOL &pc)
Setup preconditioner operator.
Additional Inherited Members
Static Public Member Functions inherited from SOL
static void SetSolTypeFromName (SOLParams &params)
Set solver type from its name.
Protected Member Functions inherited from SOL
void WarnRealRes (double relres) const
Warning for actual relative residual.
void WarnCompRes (double relres) const
Warning for computed relative residual.
void WarnDiffRes (double reldiff, double relres) const
Output relative difference and residual.
Protected Attributes inherited from SOL
const LOP * A
Coefficient matrix in Ax=b.
SOL * pcd
Preconditioner for this solver.
double norm2
Euclidean norm.
double normInf
Infinity norm.
int numIter
Number of iterations when exit.
SOLParams params
Solver parameters.
Detailed Description
Preconditioned bi-conjugate gradient stabilized method.
Definition at line 23 of file BiCGStab.hxx.
Constructor & Destructor Documentation
BiCGStab()
BiCGStab::BiCGStab () inline
Default constructor.
Definition at line 42 of file BiCGStab.hxx.
        : len(0)
        , r0star(0)
        , tmp(0)
        , apj(0)
        , asj(0)
        , pj(0)
        , rj(0)
        , sj(0)
        , ptmp(0)
        , stmp(0)
        , mp(0)
        , ms(0)
        , safe(0){};
Member Function Documentation
Clean()
void BiCGStab::Clean () override virtual
Clean up CG data allocated during Setup.
Clean up temp memory allocated for BiCGStab.
Reimplemented from SOL.
Definition at line 51 of file BiCGStab.cxx.
{
    r0star.SetValues(len, 0.0);
    tmp.SetValues(len, 0.0);
    apj.SetValues(len, 0.0);
    asj.SetValues(len, 0.0);
    pj.SetValues(len, 0.0);
    rj.SetValues(len, 0.0);
    sj.SetValues(len, 0.0);
    ptmp.SetValues(len, 0.0);
    stmp.SetValues(len, 0.0);
    ms.SetValues(len, 0.0);
    mp.SetValues(len, 0.0);
    safe.SetValues(len, 0.0);
}
References VEC::SetValues().
Setup()
FaspRetCode BiCGStab::Setup (const LOP & A) override virtual
Setup the BiCGStab method.
Allocate memory, assign param to this->param.
Reimplemented from SOL.
Definition at line 17 of file BiCGStab.cxx.
{
    // Set solver type
    SetSolType(SOLType::SOLVER_BICGSTAB);
    // Allocate memory for temporary vectors
    try {
        len = A.GetColSize();
        r0star.SetValues(len, 0.0);
        tmp.SetValues(len, 0.0);
        apj.SetValues(len, 0.0);
        asj.SetValues(len, 0.0);
        pj.SetValues(len, 0.0);
        rj.SetValues(len, 0.0);
        sj.SetValues(len, 0.0);
        ptmp.SetValues(len, 0.0);
        stmp.SetValues(len, 0.0);
        ms.SetValues(len, 0.0);
        mp.SetValues(len, 0.0);
        safe.SetValues(len, 0.0);
    } catch (std::bad_alloc& ex) {
        return FaspRetCode::ERROR_ALLOC_MEM;
    }
    // Setup the coefficient matrix
    this->A = &A;
    // Print used parameters
    if (params.verbose > PRINT_MIN) PrintParam(std::cout);
    return FaspRetCode::SUCCESS;
}
References SOL::A, ERROR_ALLOC_MEM, LOP::GetColSize(), SOL::params, SOL::SetSolType(), VEC::SetValues(), SOLVER_BICGSTAB, and SOLParams::verbose.
Solve()
FaspRetCode BiCGStab::Solve (const VEC & b, VEC & x) override virtual
Solve Ax=b using the BiCGStab method.
Preconditioned Bi-Conjugate Gradient Stabilized method. Don't check problem sizes.
Reimplemented from SOL.
Definition at line 68 of file BiCGStab.cxx.
{
    FaspRetCode errorCode = FaspRetCode::SUCCESS;
    // Declaration and definition of local variables
    const int    maxStag    = MAX_STAG_NUM;         // maximum number of stagnation
    const double solStagTol = 1e-4 * params.relTol; // solution stagnation tolerance
    int    stagStep = 0, moreStep = 0;
    double resAbs = 1.0, resRel = 1.0, denAbs = 1.0, ratio = 0.0, resAbsOld = 1.0;
    double alpha, beta, rjr0star, rjr0startmp, omega, tmp12;
    PrintHead();
    // Initialize iterative method
    numIter = 0;
    A->Apply(x, this->tmp); // A * x -> tmp
    this->rj.WAXPBY(1.0, b, -1.0, this->tmp);
    // Prepare for the main loop
    this->r0star = this->rj; // r0_{*} = r0c
    this->pj     = this->rj; // p0 = r0
    // Main BiCGStab loop
    while (numIter < params.maxIter) {
        // Start from minIter instead of 0
        if (numIter == params.minIter) {
            resAbs = rj.Norm2();
            denAbs = (CLOSE_ZERO > resAbs) ? CLOSE_ZERO : resAbs;
            resRel = resAbs / denAbs;
            if (resRel < params.relTol || resAbs < params.absTol) break;
        }
        if (numIter >= params.minIter) PrintInfo(numIter, resRel, resAbs, ratio);
        //---------------------------------------------
        // BiCGStab iteration starts from here
        //---------------------------------------------
        ++numIter; // iteration count
        // alpha_j = (rj,r0star)/(P * A * pj,r0star)
        rjr0star = this->rj.Dot(this->r0star);
        // main computational work
        A->Apply(this->pj, this->apj);
        ptmp.SetValues(len, 0.0);
        pcd->Solve(this->apj, this->ptmp);
        tmp12 = this->ptmp.Dot(this->r0star);
        if (fabs(tmp12) > 1e-40)
            alpha = rjr0star / tmp12;
        else {
            FASPXX_WARNING("Divided by zero!"); // Possible breakdown
            errorCode = FaspRetCode::ERROR_DIVIDE_ZERO;
            break;
        }
        // sj = rj - alpha_j * P * A * p_j
        this->sj.WAXPBY(1.0, this->rj, -alpha, this->ptmp);
        // omega_j = (P * A * sj,sj)/(P * A * sj,P * A * sj)
        A->Apply(this->sj, this->asj);
        stmp.SetValues(len, 0.0);
        pcd->Solve(this->asj, this->stmp);
        omega = this->stmp.Dot(this->sj) / this->stmp.Dot(this->stmp);
        // Update solution and residual
        // x_{j+1} = x_{j} + alpha_{j} * P * pj + omega_j * P * s_{j}
        mp.SetValues(len, 0.0);
        pcd->Solve(this->pj, this->mp);
        ms.SetValues(len, 0.0);
        pcd->Solve(this->sj, this->ms);
        this->tmp.WAXPBY(alpha, this->mp, omega, this->ms);
        x.XPAY(1.0, this->tmp);
        // r_{j+1} = sj - omega_j * P * A * sj
        this->rj.WAXPBY(1.0, this->sj, -omega, this->stmp);
        //---------------------------------------------
        // One step of BiCGStab iteration ends here
        //---------------------------------------------
        // Apply several checks for safety
        if (numIter >= params.minIter) {
            // Compute norm of residual and output iteration information if needed
            resAbs = rj.Norm2();
            resRel = resAbs / denAbs;
            ratio  = resAbs / resAbsOld;
            // Save the best solution so far
            if (numIter >= params.savIter && resAbs < resAbsOld) safe = x;
            // Apply stagnation checks if it converges slowly
            if (ratio > KSM_CHK_RATIO && numIter > params.minIter) {
                // Check I: if solution is close to zero, return
                // ERROR_SOLVER_SOLSTAG
                double xNorminf = x.NormInf();
                if (xNorminf < solStagTol) {
                    if (params.verbose > PRINT_MIN)
                        FASPXX_WARNING("Iteration stopped due to x vanishes!");
                    errorCode = FaspRetCode::ERROR_SOLVER_SOLSTAG;
                    break;
                }
                // Check II: if relative difference stagnated, try to restart
                double xRelDiff = fabs(alpha) * this->pj.Norm2() / x.Norm2();
                if ((stagStep <= maxStag) && (xRelDiff < solStagTol)) {
                    // Compute and update the residual before restart
                    A->Apply(x, this->rj);
                    this->rj.XPAY(-1.0, b);
                    resAbs = this->rj.Norm2();
                    resRel = resAbs / denAbs;
                    if (params.verbose > PRINT_SOME) {
                        FASPXX_WARNING("Possible iteration stagnate!");
                        WarnRealRes(resRel);
                    }
                    if (resRel < params.relTol || resAbs < params.absTol)
                        break;
                    else {
                        if (stagStep >= maxStag) {
                            if (params.verbose > PRINT_MIN)
                                FASPXX_WARNING("Iteration stopped due to stagnation!");
                            errorCode = FaspRetCode::ERROR_SOLVER_STAG;
                            break;
                        }
                        this->pj.SetValues(len, 0.0);
                        ++stagStep;
                    }
                    if (params.verbose > PRINT_SOME) {
                        WarnDiffRes(xRelDiff, resRel);
                        FASPXX_WARNING("Iteration restarted due to stagnation!");
                    }
                } // End of stagnation check!
            } // End of check I and II
            // Check III: prevent false convergence
            if (resRel < params.relTol) {
                // Compute true residual r = b - Ax and update residual
                A->Apply(x, this->rj);
                this->rj.XPAY(-1.0, b);
                // Compute residual norms and check convergence
                double resRelOld = resRel;
                resAbs           = rj.Norm2();
                resRel           = resAbs / denAbs;
                if (resRel < params.relTol || resAbs < params.absTol) break;
                if (params.verbose >= PRINT_MORE) {
                    FASPXX_WARNING("False convergence!");
                    WarnCompRes(resRelOld);
                    WarnRealRes(resRel);
                }
                if (moreStep >= params.restart) {
                    // Note: restart has different meaning here
                    if (params.verbose > PRINT_MIN)
                        FASPXX_WARNING("The tolerance might be too small!");
                    errorCode = FaspRetCode::ERROR_SOLVER_TOLSMALL;
                    break;
                }
                // Prepare for restarting method
                this->pj.SetValues(len, 0.0);
                ++moreStep;
            } // End of check!
        }
        // Prepare for the next iteration
        if (numIter < params.maxIter) {
            // Save residual for next iteration
            resAbsOld = resAbs;
            // beta_j = (r_{j+1},r0^{*}) / (r_{j},r0^{*}) * alpha_j / omega_j
            rjr0startmp = rjr0star;
            rjr0star    = this->rj.Dot(this->r0star);
            beta        = rjr0star / rjr0startmp * alpha / omega;
            // p_{j+1} = r_{j+1} + beta_j * (p_{j} - omega_j * P * A * p_{j})
            this->tmp.WAXPBY(1.0, this->pj, -omega, this->ptmp);
            this->pj.WAXPBY(1.0, this->rj, beta, this->tmp);
        }
    } // End of main BiCGStab loop
    // If minIter == numIter == maxIter (preconditioner only), skip this
    if (not(numIter == params.minIter && numIter == params.maxIter)) {
        this->norm2   = resAbs;
        this->normInf = rj.NormInf();
        PrintFinal(numIter, resRel, resAbs, ratio);
    }
    // Restore the saved best iteration if needed
    if (numIter > params.savIter) x = safe;
    return errorCode;
}
References SOL::A, SOLParams::absTol, LOP::Apply(), CLOSE_ZERO, VEC::Dot(), ERROR_DIVIDE_ZERO, FASPXX_WARNING, KSM_CHK_RATIO, MAX_STAG_NUM, SOLParams::maxIter, SOLParams::minIter, VEC::Norm2(), VEC::NormInf(), SOL::numIter, SOL::params, SOL::pcd, SOL::PrintHead(), SOL::PrintInfo(), SOLParams::relTol, SOLParams::savIter, VEC::SetValues(), SOL::Solve(), SUCCESS, SOLParams::verbose, VEC::WAXPBY(), and VEC::XPAY().
The documentation for this class was generated from the following files:
BiCGStab.hxx
BiCGStab.cxx