FASP++: Jacobi Class Reference
Jacobi Class Reference
Jacobi iterator.
#include <Iter.hxx>
Public Member Functions
Jacobi ()
Default constructor.
Jacobi (DBL weight)
Default constructor with specified weight.
~Jacobi ()=default
Default destructor.
void SetWeight (const DBL weight)
Set the weight for the Jacobi method.
FaspRetCode Setup (const MAT &A)
Setup the Jacobi method.
void Clean () override
Clean up Jacobi data allocated during Setup.
FaspRetCode Solve (const VEC &b, VEC &x) override
Solve Ax=b using the Jacobi method.
Public Member Functions inherited from SOL
SOL ()
Default constructor.
~SOL ()
Default destructor.
void SetOutput (Output verbose)
Set output level.
void SetMaxIter (int maxIter)
Set max number of iterations.
void SetMinIter (int minIter)
Set min number of iterations.
void SetSavIter (int savIter)
Set number of safe-guard iterations.
void SetRestart (int restart)
Set restart number for Krylov methods.
void SetRelTol (double relTol)
Set tolerance for relative residual.
void SetAbsTol (double absTol)
Set tolerance for absolute residual.
void SetSolType (SOLType solver)
Set solver type.
const char * GetSolType (SOLType type) const
Get solver type.
double GetNorm2 () const
Get Euclidean norm of residual.
double GetInfNorm () const
Get infinity norm of residual.
int GetIterations () const
Get number of iterations.
void PrintParam (std::ostream &out=std::cout) const
Print parameters.
void PrintHead (std::ostream &out=std::cout) const
Print out iteration information table header.
void PrintInfo (const int &iter, const double &resRel, const double &resAbs, const double &factor, std::ostream &out=std::cout) const
Print out iteration information for iterative solvers.
void PrintFinal (const int &iter, const double &resRel, const double &resAbs, const double &ratio, std::ostream &out=std::cout) const
Print out final status of an iterative method.
void PrintTime (const double duration, std::ostream &out=std::cout) const
Print out duration of solver.
virtual void SetupPCD (SOL &pc)
Setup preconditioner operator.
virtual FaspRetCode Setup (const LOP &A)
Setup the iterative method using linear opeartor.
Additional Inherited Members
Static Public Member Functions inherited from SOL
static void SetSolTypeFromName (SOLParams &params)
Set solver type from its name.
Protected Member Functions inherited from SOL
void WarnRealRes (double relres) const
Warning for actual relative residual.
void WarnCompRes (double relres) const
Warning for computed relative residual.
void WarnDiffRes (double reldiff, double relres) const
Output relative difference and residual.
Protected Attributes inherited from SOL
const LOP * A
Coefficient matrix in Ax=b.
SOL * pcd
Preconditioner for this solver.
double norm2
Euclidean norm.
double normInf
Infinity norm.
int numIter
Number of iterations when exit.
SOLParams params
Solver parameters.
Detailed Description
Jacobi iterator.
Definition at line 42 of file Iter.hxx.
Constructor & Destructor Documentation
Jacobi() [1/2]
Jacobi::Jacobi () inline
Default constructor.
Definition at line 51 of file Iter.hxx.
        : weight(1.0)
        , diagInv(1.0)
        , work(0.0){};
Jacobi() [2/2]
Jacobi::Jacobi (DBL weight)
Default constructor with specified weight.
Definition at line 23 of file Iter.cxx.
{ this->weight = weight; }
Member Function Documentation
Clean()
void Jacobi::Clean () inline override virtual
Clean up Jacobi data allocated during Setup.
Reimplemented from SOL.
Definition at line 69 of file Iter.hxx.
{};
Setup()
FaspRetCode Jacobi::Setup (const MAT & A)
Setup the Jacobi method.
Setup Jacobi preconditioner.
Definition at line 29 of file Iter.cxx.
{
    // Set solver type
    SetSolType(SOLType::SOLVER_JACOBI);
    // Allocate memory for temporary vectors
    try {
        work.SetValues(A.GetColSize(), 0.0);
    } catch (std::bad_alloc& ex) {
        return FaspRetCode::ERROR_ALLOC_MEM;
    }
    // Setup the coefficient matrix
    this->A = &A;
    // Get diagonal and compute its scaled reciprocal = 1 ./ diag * weight
    A.GetDiag(diagInv);
    diagInv.Reciprocal();
    diagInv.Scale(weight);
    // Print used parameters if necessary
    if (params.verbose > PRINT_MIN) PrintParam(std::cout);
    return FaspRetCode::SUCCESS;
}
References SOL::A, ERROR_ALLOC_MEM, LOP::GetColSize(), SOL::params, VEC::Reciprocal(), VEC::Scale(), SOL::SetSolType(), VEC::SetValues(), SOLVER_JACOBI, and SOLParams::verbose.
SetWeight()
void Jacobi::SetWeight (const DBL weight)
Set the weight for the Jacobi method.
Definition at line 26 of file Iter.cxx.
{ this->weight = weight; }
Solve()
FaspRetCode Jacobi::Solve (const VEC & b, VEC & x) override virtual
Solve Ax=b using the Jacobi method.
Solve Ax=b using the Jacobi method. Don't check problem sizes.
Reimplemented from SOL.
Definition at line 56 of file Iter.cxx.
{
    FaspRetCode errorCode = FaspRetCode::SUCCESS;
    // Declaration and definition of local variables
    double resAbs = 1.0, resRel = 1.0, denAbs = 1.0, ratio = 0.0, resAbsOld = 1.0;
    PrintHead();
    // Initialize iterative method
    numIter = 0;
    // Main Jacobi loop
    while (numIter < params.maxIter) {
        // Update residual r = b - A*x
        A->Residual(b, x, work);
        // Compute norm of residual and check whether it converges
        if (numIter >= params.minIter) {
            resAbs = work.Norm2();
            if (numIter == params.minIter)
                denAbs = (CLOSE_ZERO > resAbs) ? CLOSE_ZERO : resAbs;
            resRel = resAbs / denAbs;
            if (resRel < params.relTol || resAbs < params.absTol) break;
            ratio     = resAbs / resAbsOld;
            resAbsOld = resAbs;
            PrintInfo(numIter, resRel, resAbs, ratio);
        }
        //---------------------------------------------
        // Jacobi iteration starts from here
        //---------------------------------------------
        work.PointwiseMult(diagInv); // r = weight * r ./ d
        x += work;                   // x = x + weight * r
        ++numIter;                   // iteration count
        //---------------------------------------------
        // One step of Jacobi iteration ends here
        //---------------------------------------------
    } // End of main Jacobi loop
    // If minIter == numIter == maxIter (preconditioner only), skip this
    if (not(numIter == params.minIter && numIter == params.maxIter)) {
        A->Residual(b, x, work); // Update final residual
        this->norm2 = resAbs = work.Norm2();
        this->normInf        = work.NormInf();
        resRel               = resAbs / denAbs;
        ratio                = resAbs / resAbsOld;
        PrintFinal(numIter, resRel, resAbs, ratio);
    }
    return errorCode;
}
References SOL::A, SOLParams::absTol, CLOSE_ZERO, SOLParams::maxIter, SOLParams::minIter, SOL::norm2, VEC::Norm2(), SOL::normInf, VEC::NormInf(), SOL::numIter, SOL::params, VEC::PointwiseMult(), SOL::PrintFinal(), SOL::PrintHead(), SOL::PrintInfo(), SOLParams::relTol, LOP::Residual(), and SUCCESS.
The documentation for this class was generated from the following files:
Iter.hxx
Iter.cxx