FASP++: UMFPACK Class Reference
UMFPACK Class Reference
Interface to external direct solver: Umfpack.
#include <Umfpack.hxx>
Public Member Functions
UMFPACK ()
Default constructor.
~UMFPACK ()=default
Default destructor.
FaspRetCode Setup (const MAT &A)
Setup the UMFPACK direct solver.
FaspRetCode Solve (const VEC &b, VEC &x) override
Solve Ax=b using the the UMFPACK direct solver.
void Clean () override
Clean up UMFPACK data allocated during Setup.
Public Member Functions inherited from SOL
SOL ()
Default constructor.
~SOL ()
Default destructor.
void SetOutput (Output verbose)
Set output level.
void SetMaxIter (int maxIter)
Set max number of iterations.
void SetMinIter (int minIter)
Set min number of iterations.
void SetSavIter (int savIter)
Set number of safe-guard iterations.
void SetRestart (int restart)
Set restart number for Krylov methods.
void SetRelTol (double relTol)
Set tolerance for relative residual.
void SetAbsTol (double absTol)
Set tolerance for absolute residual.
void SetSolType (SOLType solver)
Set solver type.
const char * GetSolType (SOLType type) const
Get solver type.
double GetNorm2 () const
Get Euclidean norm of residual.
double GetInfNorm () const
Get infinity norm of residual.
int GetIterations () const
Get number of iterations.
void PrintParam (std::ostream &out=std::cout) const
Print parameters.
void PrintHead (std::ostream &out=std::cout) const
Print out iteration information table header.
void PrintInfo (const int &iter, const double &resRel, const double &resAbs, const double &factor, std::ostream &out=std::cout) const
Print out iteration information for iterative solvers.
void PrintFinal (const int &iter, const double &resRel, const double &resAbs, const double &ratio, std::ostream &out=std::cout) const
Print out final status of an iterative method.
void PrintTime (const double duration, std::ostream &out=std::cout) const
Print out duration of solver.
virtual void SetupPCD (SOL &pc)
Setup preconditioner operator.
virtual FaspRetCode Setup (const LOP &A)
Setup the iterative method using linear opeartor.
Additional Inherited Members
Static Public Member Functions inherited from SOL
static void SetSolTypeFromName (SOLParams &params)
Set solver type from its name.
Protected Member Functions inherited from SOL
void WarnRealRes (double relres) const
Warning for actual relative residual.
void WarnCompRes (double relres) const
Warning for computed relative residual.
void WarnDiffRes (double reldiff, double relres) const
Output relative difference and residual.
Protected Attributes inherited from SOL
const LOP * A
Coefficient matrix in Ax=b.
SOL * pcd
Preconditioner for this solver.
double norm2
Euclidean norm.
double normInf
Infinity norm.
int numIter
Number of iterations when exit.
SOLParams params
Solver parameters.
Detailed Description
Interface to external direct solver: Umfpack.
Definition at line 28 of file Umfpack.hxx.
Constructor & Destructor Documentation
UMFPACK()
UMFPACK::UMFPACK () inline
Default constructor.
Definition at line 42 of file Umfpack.hxx.
        : n(0)
        , m(0)
        , nnz(0)
        , Ap(nullptr)
        , Ai(nullptr)
        , Ax(nullptr)
        , Symbolic(nullptr)
        , Numeric(nullptr){};
Member Function Documentation
Clean()
void UMFPACK::Clean () override virtual
Clean up UMFPACK data allocated during Setup.
Clean up temp memory allocated for UMFPACK. Note: Must be called before reusing the class.
Reimplemented from SOL.
Definition at line 75 of file Umfpack.cxx.
{
    delete[] Ap;
    delete[] Ai;
    delete[] Ax;
    Ap = nullptr;
    Ai = nullptr;
    Ax = nullptr;
#if WITH_UMFPACK
    umfpack_di_free_numeric(&Numeric);
#endif
}
Setup()
FaspRetCode UMFPACK::Setup (const MAT & A)
Setup the UMFPACK direct solver.
Allocate memory, setup coefficient matrix of the linear system.
Definition at line 16 of file Umfpack.cxx.
{
#if WITH_UMFPACK
    int status;
    // Set solver type
    SetSolType(SOLType::UMFPACK);
    // Setup the coefficient matrix
    this->A = &A;
    // Setup data for UMFPACK ordering (column-major)
    MAT Atrans = A;
    Atrans.TransInPlace();
    n   = Atrans.GetColSize();
    m   = Atrans.GetRowSize();
    nnz = Atrans.GetNNZ();
    if (Ap != nullptr) FASPXX_ABORT("Pointer Ap is not null!");
    Ap = Atrans.GetRowPtr();
    if (Ai != nullptr) FASPXX_ABORT("Pointer Ai is not null!");
    Ai = Atrans.GetColInd();
    if (Ax != nullptr) FASPXX_ABORT("Pointer Ax is not null!");
    Ax = Atrans.GetValues();
    // Call factorizations; see 6.11 in UMFPACK manual for error code
    if (Symbolic != nullptr) FASPXX_ABORT("Pointer Symbolic is not null!");
    status = umfpack_di_symbolic(n, n, Ap, Ai, Ax, &Symbolic, NULL, NULL);
    if (status != 0) return FaspRetCode::ERROR_DSOLVER_SETUP;
    if (Numeric != nullptr) FASPXX_ABORT("Pointer Numeric is not null!");
    status = umfpack_di_numeric(Ap, Ai, Ax, Symbolic, &Numeric, NULL, NULL);
    if (status != 0) return FaspRetCode::ERROR_DSOLVER_SETUP;
    umfpack_di_free_symbolic(&Symbolic);
    return FaspRetCode::SUCCESS;
#else
    FASPXX_ABORT("External package UMFPACK not found!");
#endif
}
References SOL::A, ERROR_DSOLVER_SETUP, FASPXX_ABORT, MAT::GetColInd(), LOP::GetColSize(), MAT::GetNNZ(), MAT::GetRowPtr(), LOP::GetRowSize(), MAT::GetValues(), SOL::SetSolType(), SUCCESS, and MAT::TransInPlace().
Solve()
FaspRetCode UMFPACK::Solve (const VEC & b, VEC & x) override virtual
Solve Ax=b using the the UMFPACK direct solver.
Using the UMFPACK direct solver. Don't check problem sizes.
Reimplemented from SOL.
Definition at line 61 of file Umfpack.cxx.
{
#if WITH_UMFPACK
    int status;
    status = umfpack_di_solve(UMFPACK_A, Ap, Ai, Ax, &x[0], &b[0], Numeric, NULL, NULL);
    if (status == 0) return FaspRetCode::SUCCESS;
#else
    FASPXX_ABORT("External package UMFPACK not found!");
#endif
    return FaspRetCode::ERROR_SOLVER_TYPE;
}
References ERROR_SOLVER_TYPE, FASPXX_ABORT, and SUCCESS.
The documentation for this class was generated from the following files:
Umfpack.hxx
Umfpack.cxx