FASP++: MG Class Reference
MG Class Reference
Multigrid method in an abstract setting.
#include <MG.hxx>
Public Member Functions
MG ()
Default constructor.
~MG ()=default
Default destructor.
FaspRetCode Solve (const VEC &b, VEC &x) override
Solve Ax=b using the MG method.
void Clean () override
Clean up MG data allocated during Setup.
Public Member Functions inherited from SOL
SOL ()
Default constructor.
~SOL ()
Default destructor.
void SetOutput (Output verbose)
Set output level.
void SetMaxIter (int maxIter)
Set max number of iterations.
void SetMinIter (int minIter)
Set min number of iterations.
void SetSafeIter (int safeIter)
Set number of safe-guard iterations.
void SetRestart (int restart)
Set restart number for Krylov methods.
void SetRelTol (double relTol)
Set tolerance for relative residual.
void SetAbsTol (double absTol)
Set tolerance for absolute residual.
void SetWeight (double alpha)
Set weight for correction schemes.
void SetSolType (SOLType solver)
Set solver type.
const char * GetSolType (SOLType type) const
Get solver type.
double GetNorm2 () const
Get Euclidean norm of residual.
double GetInfNorm () const
Get infinity norm of residual.
int GetIterations () const
Get number of iterations.
void PrintParam (std::ostream &out=std::cout) const
Print parameters.
void PrintHead (std::ostream &out=std::cout) const
Print out iteration information table header.
void PrintInfo (const int &iter, const double &resRel, const double &resAbs, const double &factor, std::ostream &out=std::cout) const
Print out iteration information for iterative solvers.
void PrintFinal (const int &iter, const double &resRel, const double &resAbs, const double &ratio, std::ostream &out=std::cout) const
Print out final status of an iterative method.
void PrintTime (const double duration, std::ostream &out=std::cout) const
Print out duration of solver.
virtual void SetupPCD (SOL &pc)
Setup preconditioner operator.
virtual FaspRetCode Setup (const LOP &A)
Setup the iterative method using linear opeartor.
Public Attributes
vector< unsigned > sizes
problem sizes at all levels
vector< unsigned > cycles
number of cycles at all levels
vector< VEC > bVectors
right-hand side vectors b at all levels
vector< VEC > xVectors
solution vectors x at all levels
vector< VEC > wVectors
work vectors w at all levels
vector< SOL * > preSolvers
pointers to presmoothers at all levels
vector< SOL * > postSolvers
pointers to presmoothers at all levels
SOL * coarsestSolver
pointer to solver at coarsest level
Additional Inherited Members
Static Public Member Functions inherited from SOL
static void SetSolTypeFromName (SOLParams &params)
Set solver type from its name.
Protected Member Functions inherited from SOL
void WarnRealRes (double relres) const
Warning for actual relative residual.
void WarnCompRes (double relres) const
Warning for computed relative residual.
void WarnDiffRes (double reldiff, double relres) const
Output relative difference and residual.
Protected Attributes inherited from SOL
const LOP * A
Coefficient matrix in Ax=b.
SOL * pcd
Preconditioner for this solver.
double norm2
Euclidean norm.
double normInf
Infinity norm.
int numIter
Number of iterations when exit.
SOLParams params
solver parameters
Detailed Description
Multigrid method in an abstract setting.
Definition at line 25 of file MG.hxx.
Constructor & Destructor Documentation
MG()
MG::MG () inline
Default constructor.
Definition at line 53 of file MG.hxx.
        : numLevelsMax(20)
        , numLevelsUse(1)
        , useSymmRoperator(true){};
Member Function Documentation
Clean()
void MG::Clean () override virtual
Clean up MG data allocated during Setup.
Clean up temp memory allocated for MG.
Reimplemented from SOL.
Definition at line 133 of file MG.cxx.
{
    for (unsigned i = 0; i < numLevelsUse; ++i) {
        bVectors[i].SetValues(len, 0.0);
        xVectors[i].SetValues(len, 0.0);
        wVectors[i].SetValues(len, 0.0);
    }
}
References bVectors, wVectors, and xVectors.
Solve()
FaspRetCode MG::Solve (const VEC & b, VEC & x) override virtual
Solve Ax=b using the MG method.
Using the multigrid method. Don't check problem sizes.
Reimplemented from SOL.
Definition at line 75 of file MG.cxx.
{
    FaspRetCode errorCode = FaspRetCode::SUCCESS;
    // Declaration and definition of local variables
    double resAbs = 1.0, resRel = 1.0, denAbs = 1.0, ratio = 0.0, resAbsOld = 1.0;
    PrintHead();
    // Initialize iterative method
    numIter = 0;
    // Main Jacobi loop
    while (numIter < params.maxIter) {
        // Update residual r = b - A*x
        A->Residual(b, x, wVectors[0]);
        // Compute norm of residual and check whether it converges
        if (numIter >= params.minIter) {
            resAbs = wVectors[0].Norm2();
            if (numIter == params.minIter)
                denAbs = (CLOSE_ZERO > resAbs) ? CLOSE_ZERO : resAbs;
            resRel = resAbs / denAbs;
            if (resRel < params.relTol || resAbs < params.absTol) break;
            ratio     = resAbs / resAbsOld;
            resAbsOld = resAbs;
            PrintInfo(numIter, resRel, resAbs, ratio);
        }
        //---------------------------------------------
        // Multigrid iteration starts from here
        //---------------------------------------------
        oneCycleMultigrid(b, x); // MG cycle
        ++numIter;               // iteration count
        //---------------------------------------------
        // One step of Multigrid iteration ends here
        //---------------------------------------------
    } // End of main loop
    // If minIter == numIter == maxIter (preconditioner only), skip this
    if (not(numIter == params.minIter && numIter == params.maxIter)) {
        // Update residual r = b - A*x
        A->Residual(b, x, wVectors[0]);
        resAbs        = wVectors[0].Norm2();
        resRel        = resAbs / denAbs;
        ratio         = resAbs / resAbsOld;
        this->norm2   = resAbs;
        this->normInf = wVectors[0].NormInf();
        PrintFinal(numIter, resRel, resAbs, ratio);
    }
    return errorCode;
}
References SOL::A, SOLParams::absTol, SOLParams::maxIter, SOLParams::minIter, SOL::norm2, SOL::normInf, SOL::numIter, SOL::params, SOL::PrintFinal(), SOL::PrintHead(), SOL::PrintInfo(), SOLParams::relTol, LOP::Residual(), SUCCESS, and wVectors.
Member Data Documentation
bVectors
vector<VEC> MG::bVectors
right-hand side vectors b at all levels
Definition at line 40 of file MG.hxx.
coarsestSolver
SOL* MG::coarsestSolver
pointer to solver at coarsest level
Definition at line 46 of file MG.hxx.
cycles
vector<unsigned> MG::cycles
number of cycles at all levels
Definition at line 39 of file MG.hxx.
postSolvers
vector<SOL*> MG::postSolvers
pointers to presmoothers at all levels
Definition at line 45 of file MG.hxx.
preSolvers
vector<SOL*> MG::preSolvers
pointers to presmoothers at all levels
Definition at line 44 of file MG.hxx.
sizes
vector<unsigned> MG::sizes
problem sizes at all levels
Definition at line 38 of file MG.hxx.
wVectors
vector<VEC> MG::wVectors
work vectors w at all levels
Definition at line 42 of file MG.hxx.
xVectors
vector<VEC> MG::xVectors
solution vectors x at all levels
Definition at line 41 of file MG.hxx.
The documentation for this class was generated from the following files:
MG.hxx
MG.cxx