FASP++: CG Class Reference
CG Class Reference
Preconditioned conjugate gradient method.
#include <CG.hxx>
Public Member Functions
CG ()
Default constructor.
~CG ()=default
Default destructor.
FaspRetCode Setup (const LOP &A) override
Setup the CG method.
FaspRetCode Solve (const VEC &b, VEC &x) override
Solve Ax=b using the CG method.
void Clean () override
Clean up CG data allocated during Setup.
Public Member Functions inherited from SOL
SOL ()
Default constructor.
~SOL ()
Default destructor.
void SetOutput (Output verbose)
Set output level.
void SetMaxIter (int maxIter)
Set max number of iterations.
void SetMinIter (int minIter)
Set min number of iterations.
void SetSafeIter (int safeIter)
Set number of safe-guard iterations.
void SetRestart (int restart)
Set restart number for Krylov methods.
void SetRelTol (double relTol)
Set tolerance for relative residual.
void SetAbsTol (double absTol)
Set tolerance for absolute residual.
void SetWeight (double alpha)
Set weight for correction schemes.
void SetSolType (SOLType solver)
Set solver type.
const char * GetSolType (SOLType type) const
Get solver type.
double GetNorm2 () const
Get Euclidean norm of residual.
double GetInfNorm () const
Get infinity norm of residual.
int GetIterations () const
Get number of iterations.
void PrintParam (std::ostream &out=std::cout) const
Print parameters.
void PrintHead (std::ostream &out=std::cout) const
Print out iteration information table header.
void PrintInfo (const int &iter, const double &resRel, const double &resAbs, const double &factor, std::ostream &out=std::cout) const
Print out iteration information for iterative solvers.
void PrintFinal (const int &iter, const double &resRel, const double &resAbs, const double &ratio, std::ostream &out=std::cout) const
Print out final status of an iterative method.
void PrintTime (const double duration, std::ostream &out=std::cout) const
Print out duration of solver.
virtual void SetupPCD (SOL &pc)
Setup preconditioner operator.
Additional Inherited Members
Static Public Member Functions inherited from SOL
static void SetSolTypeFromName (SOLParams &params)
Set solver type from its name.
Protected Member Functions inherited from SOL
void WarnRealRes (double relres) const
Warning for actual relative residual.
void WarnCompRes (double relres) const
Warning for computed relative residual.
void WarnDiffRes (double reldiff, double relres) const
Output relative difference and residual.
Protected Attributes inherited from SOL
const LOP * A
Coefficient matrix in Ax=b.
SOL * pcd
Preconditioner for this solver.
double norm2
Euclidean norm.
double normInf
Infinity norm.
int numIter
Number of iterations when exit.
SOLParams params
solver parameters
Detailed Description
Preconditioned conjugate gradient method.
Definition at line 23 of file CG.hxx.
Constructor & Destructor Documentation
CG()
CG::CG () inline
Default constructor.
Definition at line 35 of file CG.hxx.
        : len(0)
        , rk(0)
        , pk(0)
        , zk(0)
        , ax(0)
        , safe(0){};
Member Function Documentation
Clean()
void CG::Clean () override virtual
Clean up CG data allocated during Setup.
Clean up temp memory allocated for CG.
Reimplemented from SOL.
Definition at line 44 of file CG.cxx.
{
    zk.SetValues(len, 0.0);
    pk.SetValues(len, 0.0);
    rk.SetValues(len, 0.0);
    ax.SetValues(len, 0.0);
    safe.SetValues(len, 0.0);
}
References VEC::SetValues().
Setup()
FaspRetCode CG::Setup (const LOP & A) override virtual
Setup the CG method.
Allocate memory, setup coefficient matrix of the linear system.
Reimplemented from SOL.
Definition at line 17 of file CG.cxx.
{
    // Set solver type
    SetSolType(SOLType::CG);
    // Allocate memory for temporary vectors
    try {
        len = A.GetColSize();
        zk.SetValues(len, 0.0);
        pk.SetValues(len, 0.0);
        rk.SetValues(len, 0.0);
        ax.SetValues(len, 0.0);
        safe.SetValues(len, 0.0);
    } catch (std::bad_alloc& ex) {
        return FaspRetCode::ERROR_ALLOC_MEM;
    }
    // Setup the coefficient matrix
    this->A = &A;
    // Print used parameters
    if (params.verbose > PRINT_MIN) PrintParam(std::cout);
    return FaspRetCode::SUCCESS;
}
References SOL::A, CG, ERROR_ALLOC_MEM, LOP::GetColSize(), SOL::params, SOL::SetSolType(), VEC::SetValues(), and SOLParams::verbose.
Solve()
FaspRetCode CG::Solve (const VEC & b, VEC & x) override virtual
Solve Ax=b using the CG method.
Using the Conjugate Gradient method. Don't check problem sizes.
Reimplemented from SOL.
Definition at line 54 of file CG.cxx.
{
    FaspRetCode errorCode = FaspRetCode::SUCCESS;
    // Local variables
    const int    maxStag    = MAX_STAG_NUM;         // max number of stagnation checks
    const double solStagTol = 1e-4 * params.relTol; // solution stagnation tolerance
    const double solZeroTol = CLOSE_ZERO;           // solution close to zero tolerance
    int    stagStep = 0, moreStep = 0;
    double resAbs = 1.0, resRel = 1.0, denAbs = 1.0, ratio = 0.0, resAbsOld = 1.0;
    double alpha, beta, tmpa, tmpb;
    PrintHead();
    // Initialize iterative method
    numIter = 0;
    A->Apply(x, rk);  // A * x -> rk
    rk.XPAY(-1.0, b); // b - rk -> rk
    // Preconditioned search direction
    zk.SetValues(len, 0.0); // initialize zk = 0
    pcd->Solve(rk, zk);     // preconditioning: B(r_k) -> z_k
    // Prepare for the main loop
    pk   = zk;
    tmpa = zk.Dot(rk);
    // Main CG loop
    while (numIter < params.maxIter) {
        // Start checking from minIter instead of 0
        if (numIter == params.minIter) {
            resAbs    = rk.Norm2();
            resAbsOld = resAbs; // save initial residual
            denAbs    = (CLOSE_ZERO > resAbs) ? CLOSE_ZERO : resAbs;
            resRel    = resAbs / denAbs;
            if (resRel < params.relTol || resAbs < params.absTol) break;
        }
        if (numIter >= params.minIter) PrintInfo(numIter, resRel, resAbs, ratio);
        //---------------------------------------------
        // CG iteration starts from here
        //---------------------------------------------
        ++numIter; // iteration count
        A->Apply(pk, ax); // ax = A * p_k, main computational work
        // alpha_k = (z_{k-1}, r_{k-1})/(A*p_{k-1},p_{k-1})
        tmpb = ax.Dot(pk);
        if (fabs(tmpb) > CLOSE_ZERO * CLOSE_ZERO)
            alpha = tmpa / tmpb;
        else {
            FASPXX_WARNING("Divided by zero!");
            errorCode = FaspRetCode::ERROR_DIVIDE_ZERO;
            break;
        }
        // Update solution and residual
        x.AXPY(alpha, pk);   // x_k = x_{k-1} + alpha_k*p_{k-1}
        rk.AXPY(-alpha, ax); // r_k = r_{k-1} - alpha_k*A*p_{k-1}
        //---------------------------------------------
        // One step of CG iteration ends here
        //---------------------------------------------
        // Apply several checks for robustness
        if (numIter >= params.minIter) {
            // Compute norm of residual and output iteration information if needed
            resAbs = rk.Norm2();
            resRel = resAbs / denAbs;
            ratio  = resAbs / resAbsOld; // convergence ratio between two steps
            // Save the best solution so far
            if (numIter >= params.safeIter && resAbs < resAbsOld) safe = x;
            // Apply stagnation checks if it converges slowly
            if (ratio > KSM_CHK_RATIO) {
                // Check I: if solution is close to zero, return ERROR_SOLVER_SOLSTAG
                double xNormInf = x.NormInf();
                if (xNormInf < solZeroTol) {
                    if (params.verbose > PRINT_MIN)
                        FASPXX_WARNING("Iteration stopped due to x vanishes!");
                    errorCode = FaspRetCode::ERROR_SOLVER_SOLSTAG;
                    break;
                }
                // Check II: if relative difference close to zero, try to restart
                double xRelDiff = fabs(alpha) * this->pk.Norm2() / x.Norm2();
                if ((stagStep <= maxStag) && (xRelDiff < solStagTol)) {
                    // Compute and update the residual before restart
                    A->Apply(x, this->rk);
                    this->rk.XPAY(-1.0, b);
                    resAbs = this->rk.Norm2();
                    resRel = resAbs / denAbs;
                    if (params.verbose > PRINT_SOME) {
                        FASPXX_WARNING("Possible iteration stagnate!");
                        WarnRealRes(resRel);
                    }
                    if (resRel < params.relTol || resAbs < params.absTol)
                        break;
                    else {
                        if (stagStep >= maxStag) {
                            if (params.verbose > PRINT_MIN)
                                FASPXX_WARNING("Iteration stopped due to stagnation!");
                            errorCode = FaspRetCode::ERROR_SOLVER_STAG;
                            break;
                        }
                        this->pk.SetValues(len, 0.0);
                        ++stagStep;
                    }
                    if (params.verbose > PRINT_SOME) {
                        WarnDiffRes(xRelDiff, resRel);
                        FASPXX_WARNING("Iteration restarted due to stagnation!");
                    }
                } // End of stagnation check!
            } // End of check I and II
            // Check III: prevent false convergence!!!
            if (resRel < params.relTol) {
                // Compute and update the true residual r = b - Ax
                A->Apply(x, this->rk);
                this->rk.XPAY(-1.0, b);
                // Compute residual norms and check convergence
                double resRelOld = resRel;
                resAbs           = rk.Norm2();
                resRel           = resAbs / denAbs;
                if (resRel < params.relTol || resAbs < params.absTol) break;
                // If false converged, print out warning messages
                if (params.verbose >= PRINT_MORE) {
                    FASPXX_WARNING("False convergence!");
                    WarnCompRes(resRelOld);
                    WarnRealRes(resRel);
                }
                if (moreStep >= params.restart) {
                    // Note: restart has different meaning here
                    if (params.verbose > PRINT_MIN)
                        FASPXX_WARNING("The tolerance is too small!");
                    errorCode = FaspRetCode::ERROR_SOLVER_TOLSMALL;
                    break;
                }
                // Prepare for restarting method
                this->pk.SetValues(0.0);
                ++moreStep;
            } // End of check!
        }
        // Prepare for the next iteration
        if (numIter < params.maxIter) {
            // Save the residual for next iteration
            resAbsOld = resAbs;
            // Apply preconditioner z_k = B(r_k)
            zk.SetValues(len, 0.0);
            pcd->Solve(rk, zk);
            // Compute beta_k = (z_k, r_k) / (z_{k-1}, r_{k-1})
            tmpb = zk.Dot(rk);
            beta = tmpb / tmpa;
            tmpa = tmpb;
            // Compute p_k = z_k + beta_k*p_{k-1}
            pk.XPAY(beta, zk);
        }
    } // End of main CG loop
    // If minIter == numIter == maxIter (preconditioner only), skip this
    if (not(numIter == params.minIter && numIter == params.maxIter)) {
        this->norm2   = resAbs;
        this->normInf = rk.NormInf();
        PrintFinal(numIter, resRel, resAbs, ratio);
    }
    // Restore the saved best iteration if needed
    if (numIter > params.safeIter) x = safe;
    return errorCode;
}
References SOL::A, SOLParams::absTol, LOP::Apply(), VEC::AXPY(), VEC::Dot(), ERROR_DIVIDE_ZERO, FASPXX_WARNING, SOLParams::maxIter, SOLParams::minIter, VEC::Norm2(), VEC::NormInf(), SOL::numIter, SOL::params, SOL::pcd, SOL::PrintHead(), SOL::PrintInfo(), SOLParams::relTol, SOLParams::safeIter, VEC::SetValues(), SOL::Solve(), SUCCESS, SOLParams::verbose, and VEC::XPAY().
The documentation for this class was generated from the following files:
CG.hxx
CG.cxx