FASP++: FaspRunTime Class Reference
FaspRunTime Class Reference
Run-time exception capturing class.
#include <RetCode.hxx>
Public Member Functions
FaspRunTime (const FaspRetCode code_, const char *file_, const char *func_, const unsigned int line_)
Default constructor.
const char * GetFile () const
return thrown file name
const char * GetFunc () const
return thrown function name
unsigned int GetLine () const
return thrown line number
void LogExcep (std::ostream &stream=std::cout) const
Log exception messages in a file or to the screen.
Public Attributes
const FaspRetCode errorCode
Error Code.
Detailed Description
Run-time exception capturing class.
Definition at line 58 of file RetCode.hxx.
Constructor & Destructor Documentation
FaspRunTime()
FaspRunTime::FaspRunTime (const FaspRetCode code_, const char * file_, const char * func_, const unsigned int line_) inline
Default constructor.
Definition at line 71 of file RetCode.hxx.
        : std::runtime_error(GetRetCode(code_))
        , file(file_)
        , func(func_)
        , line(line_)
        , errorCode(code_)
    {
    }
Member Function Documentation
GetFile()
const char * FaspRunTime::GetFile () const inline
return thrown file name
Definition at line 82 of file RetCode.hxx.
GetFunc()
const char * FaspRunTime::GetFunc () const inline
return thrown function name
Definition at line 83 of file RetCode.hxx.
GetLine()
unsigned int FaspRunTime::GetLine () const inline
return thrown line number
Definition at line 84 of file RetCode.hxx.
LogExcep()
void FaspRunTime::LogExcep (std::ostream & stream = std::cout) const
Log exception messages in a file or to the screen.
Definition at line 86 of file RetCode.cxx.
{
    stream << "### ERROR: " << this->what() << std::endl;
    stream << "### ERROR: Check " << this->GetFile() << " in " << this->GetFunc()
           << "( ) at Line " << this->GetLine() << std::endl;
}
References GetFile(), GetFunc(), and GetLine().
Member Data Documentation
errorCode
const FaspRetCode FaspRunTime::errorCode
Error Code.
Definition at line 67 of file RetCode.hxx.
The documentation for this class was generated from the following files:
RetCode.hxx
RetCode.cxx