FASP++: Parameters Class Reference
Parameters Class Reference
Solver parameters.
#include <Param.hxx>
Public Member Functions
Parameters (int _argc, const char *_argv[])
Default constructor.
~Parameters ()=default
Default destructor.
void AddParam (const std::string &name, const std::string &help, bool *ptr, int marker=0)
Add a bool type parameter.
void AddParam (const std::string &name, const std::string &help, USI *ptr, int marker=0)
Add a unsigned int type parameter.
void AddParam (const std::string &name, const std::string &help, INT *ptr, int marker=0)
Add an int type parameter.
void AddParam (const std::string &name, const std::string &help, double *ptr, int marker=0)
Add a double type parameter.
void AddParam (const std::string &name, const std::string &help, std::string *ptr, int marker=0)
Add a string type parameter.
void AddParam (const std::string &name, const std::string &help, Output *ptr, int marker=0)
Add a Output type parameter.
void Parse ()
Parse the parameters.
void SetSOLParams (SOLParams &solParam)
Set SOLParams for solvers.
void SetSOLParams (SOLParams &solParam, SOLParams &pcdParam)
Set SOLParams for solvers and preconditioners.
void PrintUserParams (std::ostream &out) const
Print original params (before merge or parse) in user program.
void PrintFileParams (std::ostream &out) const
Print parameters coming from an option file.
void PrintCommandLineParams (std::ostream &out) const
Print parameters coming from command line input.
void Print (std::ostream &out=std::cout) const
Print parameters used in user code (after merge or parse).
void PrintHelp (std::ostream &out=std::cout) const
Print the help messages for Param.
Detailed Description
Solver parameters.
Definition at line 83 of file Param.hxx.
Constructor & Destructor Documentation
Parameters()
Parameters::Parameters (int _argc, const char * _argv[]) inline
Default constructor.
Definition at line 167 of file Param.hxx.
        : argc(_argc)
        , argv(_argv)
    {
    }
Member Function Documentation
AddParam() [1/6]
void Parameters::AddParam (const std::string & name, const std::string & help, bool * ptr, int marker = 0)
Add a bool type parameter.
Bool type parameter.
Definition at line 186 of file Param.cxx.
{
    paramsUser.emplace_back(BoolType, name, help, ptr, marker);
}
AddParam() [2/6]
void Parameters::AddParam (const std::string & name, const std::string & help, double * ptr, int marker = 0)
Add a double type parameter.
Double type parameter.
Definition at line 207 of file Param.cxx.
{
    paramsUser.emplace_back(DoubleType, name, help, ptr, marker);
}
AddParam() [3/6]
void Parameters::AddParam (const std::string & name, const std::string & help, INT * ptr, int marker = 0)
Add an int type parameter.
Int type parameter.
Definition at line 193 of file Param.cxx.
{
    paramsUser.emplace_back(IntType, name, help, ptr, marker);
}
AddParam() [4/6]
void Parameters::AddParam (const std::string & name, const std::string & help, Output * ptr, int marker = 0)
Add a Output type parameter.
Output type parameter.
Definition at line 221 of file Param.cxx.
{
    paramsUser.emplace_back(OutputType, name, help, ptr, marker);
}
AddParam() [5/6]
void Parameters::AddParam (const std::string & name, const std::string & help, std::string * ptr, int marker = 0)
Add a string type parameter.
String type parameter.
Definition at line 214 of file Param.cxx.
{
    paramsUser.emplace_back(StringType, name, help, ptr, marker);
}
AddParam() [6/6]
void Parameters::AddParam (const std::string & name, const std::string & help, USI * ptr, int marker = 0)
Add a unsigned int type parameter.
Unsigned int type parameter.
Definition at line 200 of file Param.cxx.
{
    paramsUser.emplace_back(IntType, name, help, ptr, marker);
}
Parse()
void Parameters::Parse ()
Parse the parameters.
Main entrance point for reading and handling parameters.
Definition at line 228 of file Param.cxx.
{
    // Read parameters
    ReadFromCommandLine();
    ReadFromFile();
    // Save the original and then merge
    SaveUserParams(paramsUserOrg);
    MergeParams();
}
Print()
void Parameters::Print (std::ostream & out = std::cout) const
Print parameters used in user code (after merge or parse).
Print parameters used with width adapt to the names.
Definition at line 308 of file Param.cxx.
{
    size_t max_len = 0;
    for (const auto& itm : paramsUser) {
        if (itm.paramName.length() > max_len) max_len = itm.paramName.length();
    }
    static std::string indent = "   ";
    out << "---------------------------------------------\n"
        << "Parameters used in the program\n"
        << "---------------------------------------------\n";
    for (const auto& itm : paramsUser) {
        out << indent << std::setw(max_len) << std::left << itm.paramName << " [";
        switch (itm.paramType) {
            case BoolType:
                out << std::boolalpha << *((bool*)(itm.paramPtr))
                    << std::resetiosflags(out.flags());
                break;
            case IntType:
                out << *((int*)itm.paramPtr);
                break;
            case DoubleType:
                out << *((double*)itm.paramPtr);
                break;
            case StringType:
                out << *((std::string*)itm.paramPtr);
                break;
            case OutputType:
                out << *((Output*)(itm.paramPtr));
                break;
        }
        out << "]\n";
    }
    out << '\n';
}
PrintCommandLineParams()
void Parameters::PrintCommandLineParams (std::ostream & out) const
Print parameters coming from command line input.
Definition at line 284 of file Param.cxx.
{
    size_t max_len = 0;
    for (const auto& itm : paramsCML) {
        if (itm.first.length() > max_len) max_len = itm.first.length();
    }
    static std::string indent = "   ";
    out << "---------------------------------------------\n"
        << "Parameters from the command line input\n"
        << "---------------------------------------------\n";
    for (const auto& itm : paramsCML) {
        out << indent << std::setw(max_len) << std::left << itm.first << " ["
            << itm.second << "]\n";
    }
    out << std::endl;
}
PrintFileParams()
void Parameters::PrintFileParams (std::ostream & out) const
Print parameters coming from an option file.
Definition at line 261 of file Param.cxx.
{
    size_t max_len = 0;
    for (const auto& itm : paramsFile) {
        if (itm.first.length() > max_len) max_len = itm.first.length();
    }
    std::string options_file;
    for (const auto& itm : paramsUser) {
        if (itm.paramMarker == 2) options_file = *(std::string*)itm.paramPtr;
    }
    static std::string indent = "   ";
    out << "---------------------------------------------\n"
        << "Parameters from file " << options_file << ":\n"
        << "---------------------------------------------\n";
    for (const auto& itm : paramsFile) {
        out << indent << std::setw(max_len) << std::left << itm.first << " ["
            << itm.second << "]\n";
    }
    out << std::endl;
}
PrintHelp()
void Parameters::PrintHelp (std::ostream & out = std::cout) const
Print the help messages for Param.
Print out usage help for command line.
Definition at line 346 of file Param.cxx.
{
    static const char* indent  = "   ";
    static const char* types[] = {"<bool>", "<int>", "<double>", "<string>",
                                  "<Output>"};
    size_t max_len = 0;
    for (const auto& itm : paramsUser) {
        if (itm.paramName.length() > max_len) max_len = itm.paramName.length();
    }
    out << "Usage: " << argv[0] << " [options] ...\n"
        << "Options:\n";
    for (const auto& itm : paramsUser) {
        out << indent << std::setw(max_len) << std::left << itm.paramName << " "
            << std::setw(8) << types[itm.paramType];
        if (itm.paramMarker == 0)
            out << ", optional  ";
        else if (itm.paramMarker == 1)
            out << ", required  ";
        else
            out << ", from file ";
        if (!itm.paramHelp.empty()) out << " :  " << itm.paramHelp;
        out << ", default = [";
        switch (itm.paramType) {
            case BoolType:
                out << std::boolalpha << *(bool*)(itm.paramPtr)
                    << std::setiosflags(out.flags());
                break;
            case IntType:
                out << *(int*)(itm.paramPtr);
                break;
            case DoubleType:
                out << *(double*)(itm.paramPtr);
                break;
            case StringType:
                out << *((std::string*)itm.paramPtr);
                break;
            case OutputType:
                out << *(Output*)(itm.paramPtr);
                break;
        }
        out << "]\n";
    }
}
PrintUserParams()
void Parameters::PrintUserParams (std::ostream & out) const
Print original params (before merge or parse) in user program.
Definition at line 302 of file Param.cxx.
{
    out << paramsUserOrg << std::endl;
}
SetSOLParams() [1/2]
void Parameters::SetSOLParams (SOLParams & solParam)
Set SOLParams for solvers.
Definition at line 240 of file Param.cxx.
{
    this->AddParam("-algName", "Name of solver", &solParam.algName);
    this->AddParam("-maxIter", "Max iteration steps", &solParam.maxIter);
    this->AddParam("-minIter", "Min iteration steps", &solParam.minIter);
    this->AddParam("-savIter", "Safe-guard steps", &solParam.savIter);
    this->AddParam("-restart", "Restart number", &solParam.restart);
    this->AddParam("-resRel", "Relative residual tolerance", &solParam.relTol);
    this->AddParam("-resAbs", "Absolute residual tolerance", &solParam.absTol);
    this->AddParam("-verbose", "Verbose level", &solParam.verbose);
}
References SOLParams::absTol, AddParam(), SOLParams::algName, SOLParams::maxIter, SOLParams::minIter, SOLParams::relTol, SOLParams::restart, SOLParams::savIter, and SOLParams::verbose.
SetSOLParams() [2/2]
void Parameters::SetSOLParams (SOLParams & solParam, SOLParams & pcdParam)
Set SOLParams for solvers and preconditioners.
Definition at line 253 of file Param.cxx.
{
    SetSOLParams(solParam);
    this->AddParam("-pcdIter", "Preconditioner steps", &pcdParam.maxIter);
    // TODO: Add more parameters for preconditioners here!
}
References AddParam(), SOLParams::maxIter, and SetSOLParams().
The documentation for this class was generated from the following files:
Param.hxx
Param.cxx