FASP++: GMRES Class Reference
GMRES Class Reference
Preconditioned generalized minimal residual method.
#include <GMRES.hxx>
Public Member Functions
GMRES ()
Default constructor.
~GMRES ()=default
Default destructor.
void SetMaxMinRestart (const int maxRestart, const int minRestart)
Set the maximum and minmum restart numbers for variable GMRES.
FaspRetCode Setup (const LOP &A) override
Setup the GMRES method.
void Clean () override
Clean up GMRES data allocated during setup.
FaspRetCode RSolve (const VEC &b, VEC &x)
Right-preconditioned GMRES solver.
FaspRetCode LSolve (const VEC &b, VEC &x)
Left-preconditioned GMRES slover.
Public Member Functions inherited from SOL
SOL ()
Default constructor.
~SOL ()
Default destructor.
void SetOutput (Output verbose)
Set output level.
void SetMaxIter (int maxIter)
Set max number of iterations.
void SetMinIter (int minIter)
Set min number of iterations.
void SetSafeIter (int safeIter)
Set number of safe-guard iterations.
void SetRestart (int restart)
Set restart number for Krylov methods.
void SetRelTol (double relTol)
Set tolerance for relative residual.
void SetAbsTol (double absTol)
Set tolerance for absolute residual.
void SetWeight (double alpha)
Set weight for correction schemes.
void SetSolType (SOLType solver)
Set solver type.
const char * GetSolType (SOLType type) const
Get solver type.
double GetNorm2 () const
Get Euclidean norm of residual.
double GetInfNorm () const
Get infinity norm of residual.
int GetIterations () const
Get number of iterations.
void PrintParam (std::ostream &out=std::cout) const
Print parameters.
void PrintHead (std::ostream &out=std::cout) const
Print out iteration information table header.
void PrintInfo (const int &iter, const double &resRel, const double &resAbs, const double &factor, std::ostream &out=std::cout) const
Print out iteration information for iterative solvers.
void PrintFinal (const int &iter, const double &resRel, const double &resAbs, const double &ratio, std::ostream &out=std::cout) const
Print out final status of an iterative method.
void PrintTime (const double duration, std::ostream &out=std::cout) const
Print out duration of solver.
virtual void SetPC (SOL &pc)
Setup preconditioner operator.
Additional Inherited Members
Static Public Member Functions inherited from SOL
static void SetSolTypeFromName (SOLParams &params)
Set solver type from its name.
Protected Member Functions inherited from SOL
void WarnRealRes (double relres) const
Warning for actual relative residual.
void WarnCompRes (double relres) const
Warning for computed relative residual.
void WarnDiffRes (double reldiff, double relres) const
Output relative difference and residual.
Protected Attributes inherited from SOL
const LOP * A
Coefficient matrix in Ax=b.
SOL * pc
Preconditioner for this solver.
double norm2
Euclidean norm.
double normInf
Infinity norm.
int numIter
Number of iterations when exit.
SOLParams params
solver parameters
Detailed Description
Preconditioned generalized minimal residual method.
Constructor & Destructor Documentation
GMRES()
GMRES::GMRES () inline
Default constructor.
        : wk(0)
        , safe(0)
        , tmp(0)
        , hh(0)
        , hsin(0)
        , hcos(0)
        , var(0)
        , maxRestart{30}
        , minRestart(10){};
Member Function Documentation
Clean()
void GMRES::Clean () override virtual
Clean up GMRES data allocated during setup.
Reimplemented from SOL.
{
    restart = params.restart; // restore restart value
    if (restart > maxRestart)
        restart = maxRestart;
    else if (restart < minRestart)
        restart = minRestart;
    wk.SetValues(len, 0.0);
    tmp.SetValues(len, 0.0);
    safe.SetValues(len, 0.0);
    var.assign(len, 0.0);
    hcos.assign(maxRestart + 1, 0.0);
    hsin.assign(maxRestart, 0.0);
    hh.resize(maxRestart + 1);
    for (int j = 0; j < maxRestart + 1; ++j) hh[j].assign(maxRestart, 0.0);
    V.assign(maxRestart + 1, safe);
}
References SOL::params, SOLParams::restart, and VEC::SetValues().
LSolve()
FaspRetCode GMRES::LSolve (const VEC & b, VEC & x)
Left-preconditioned GMRES slover.
Solve Ax=b using the left preconditioned GMRES method.
{
    FaspRetCode errorCode = FaspRetCode::SUCCESS;
    // local variables
    double gamma, t, ri, rj, cr = 1.0;
    double resAbs = 1.0, resRel = 1.0, denAbs = 1.0, ratio = 0.0, resAbsOld;
    int    count, count_1;
    PrintHead();
    // Initialize iterative method
    numIter = 0;
    safe    = x;
    // Initialize residual norm
    A->Apply(x, tmp);  // A * x -> tmp
    tmp.XPAY(-1.0, b); // b - tmp -> tmp
    ri = tmp.Norm2();
    // Apply preconditioner
    V[0].SetValues(len, 0.0);
    pc->Solve(tmp, V[0]);
    resAbs = V[0].Norm2();
    denAbs = (CLOSE_ZERO > resAbs) ? CLOSE_ZERO : resAbs;
    // GMRES(m) outer iteration
    while (numIter < params.maxIter) {
        // Start checking from minIter instead of 0
        if (numIter == params.minIter) {
            resRel    = resAbs / denAbs;
            resAbsOld = resAbs;
            if (resRel < params.relTol || resAbs < params.absTol) break;
        }
        // Initial search direction: r / ||r||
        if (resAbs < SMALL) break; // Residual is too small
        var[0] = resAbs;
        V[0].Scale(1 / resAbs);
        // RESTART CYCLE (left-preconditioning)
        count = 0;
        while (count < restart && numIter < params.maxIter) {
            if (numIter >= params.minIter) PrintInfo(numIter, resRel, resAbs, ratio);
            //---------------------------------------------
            // GMRES(m) inner iteration starts from here
            //---------------------------------------------
            ++numIter;         // total iteration number
            count_1 = count++; // inner iteration number
            A->Apply(V[count_1], tmp);
            V[count].SetValues(len, 0.0);
            pc->Solve(tmp, V[count]); // apply preconditioner
            // Modified Gram-Schmidt orthogonalization
            for (int j = 0; j < count; ++j) {
                hh[j][count_1] = V[count].Dot(V[j]);
                V[count].AXPBY(1.0, -hh[j][count_1], V[j]);
            }
            t                  = V[count].Norm2();
            hh[count][count_1] = t;
            // if t=0, we get solution subspace
            if (fabs(t) > SMALL)
                V[count].Scale(1.0 / t);
            else
                break;
            for (int j = 1; j < count; ++j) {
                t                  = hh[j - 1][count_1];
                hh[j - 1][count_1] = hsin[j - 1] * hh[j][count_1] + hcos[j - 1] * t;
                hh[j][count_1]     = -hsin[j - 1] * t + hcos[j - 1] * hh[j][count_1];
            }
            t = hh[count][count_1] * hh[count][count_1];
            t += hh[count_1][count_1] * hh[count_1][count_1];
            t = sqrt(t);
            gamma                = t > SMALL ? t : SMALL;
            hcos[count_1]        = hh[count_1][count_1] / gamma;
            hsin[count_1]        = hh[count][count_1] / gamma;
            hh[count_1][count_1] = hsin[count_1] * hh[count][count_1] +
                                   hcos[count_1] * hh[count_1][count_1];
            var[count]   = -hsin[count_1] * var[count_1];
            var[count_1] = hcos[count_1] * var[count_1];
            resAbs       = fabs(var[count]);
            ratio        = resAbs / resAbsOld;
            resAbsOld    = resAbs;
            resRel       = resAbs / denAbs;
            // Exit restart cycle if reaches tolerance
            if ((resAbs < params.absTol || resRel < params.relTol) &&
                numIter > params.minIter)
                break;
        } // End of restart cycle
        // Compute solution, first solve upper triangular system
        var[count_1] = var[count_1] / hh[count_1][count_1];
        for (int k = count - 2; k >= 0; --k) {
            t = 0.0;
            for (int j = k + 1; j < count; ++j) t -= hh[k][j] * var[j];
            t += var[k];
            var[k] = t / hh[k][k];
        }
        wk = V[count_1];
        wk.Scale(var[count_1]);
        for (int j = count - 2; j >= 0; --j) wk.AXPBY(1.0, var[j], V[j]);
        // Update iterative solution
        x.AXPY(1.0, wk);
        // Save the best solution so far
        if (numIter >= params.safeIter && resAbs < resAbsOld) safe = x;
        // Check whether exceeds maximal number of iterations
        if (numIter > params.maxIter) {
            errorCode = FaspRetCode::ERROR_SOLVER_MAXIT;
            break;
        }
        //---------------------------------------------
        // Prepare for the next iteration
        //---------------------------------------------
        A->Apply(x, tmp);  // A * x -> tmp
        tmp.XPAY(-1.0, b); // b - tmp -> tmp
        rj = tmp.Norm2();
        // Apply preconditioner
        V[0].SetValues(len, 0.0);
        pc->Solve(tmp, V[0]);
        // Check whether converged
        resAbs = V[0].Norm2();
        resRel = resAbs / denAbs;
        if ((resRel < params.relTol || resAbs < params.absTol) &&
            numIter >= params.minIter)
            break;
        // Choose restart number adaptively
        cr = rj / ri;
        ri = rj;
        if (cr > max_cr)
            restart = maxRestart;
        else if (cr < max_cr && cr > min_cr) {
            if (restart - decrease > minRestart)
                restart -= decrease;
            else
                restart = maxRestart;
        }
    } // End of main while loop
    // If minIter == numIter == maxIter (preconditioner only), skip this
    if (not(numIter == params.minIter && numIter == params.maxIter)) {
        norm2   = tmp.Norm2();
        normInf = tmp.NormInf();
        PrintFinal(numIter, resRel, resAbs, ratio);
    }
    // Restore the saved best iteration if needed
    if (numIter > params.safeIter) x = safe;
    return errorCode;
}
References SOL::A, SOLParams::absTol, LOP::Apply(), VEC::AXPBY(), VEC::AXPY(), CLOSE_ZERO, ERROR_SOLVER_MAXIT, SOLParams::maxIter, SOLParams::minIter, SOL::norm2, VEC::Norm2(), SOL::normInf, VEC::NormInf(), SOL::numIter, SOL::params, SOL::pc, SOL::PrintFinal(), SOL::PrintHead(), SOL::PrintInfo(), SOLParams::relTol, SOLParams::safeIter, VEC::Scale(), SMALL, SOL::Solve(), SUCCESS, and VEC::XPAY().
RSolve()
FaspRetCode GMRES::RSolve (const VEC & b, VEC & x)
Right-preconditioned GMRES solver.
Solve Ax=b using the right preconditioned GMRES method.
{
    FaspRetCode errorCode = FaspRetCode::SUCCESS;
    // local variables
    double gamma, t, ri, rj, cr = 1.0;
    double resAbs = 1.0, resRel = 1.0, denAbs = 1.0, ratio = 0.0, resAbsOld;
    int    count, count_1;
    PrintHead();
    // Initialize iterative method
    numIter = 0;
    safe    = x;
    // Initialize residual and its norm
    A->Apply(x, V[0]);  // A * x -> V[0]
    V[0].XPAY(-1.0, b); // b - V[0] -> V[0]
    resAbs = ri = V[0].Norm2();
    denAbs      = (CLOSE_ZERO > resAbs) ? CLOSE_ZERO : resAbs;
    // GMRES(m) outer iteration
    while (numIter < params.maxIter) {
        // Start checking from minIter instead of 0
        if (numIter == params.minIter) {
            resRel    = resAbs / denAbs;
            resAbsOld = resAbs;
            if (resRel < params.relTol || resAbs < params.absTol) break;
        }
        // Initial search direction: r / ||r||
        if (resAbs < SMALL) break; // Residual is too small
        var[0] = resAbs;
        V[0].Scale(1 / resAbs);
        // RESTART CYCLE (right-preconditioning)
        count = 0;
        while (count < restart && numIter < params.maxIter) {
            if (numIter >= params.minIter) PrintInfo(numIter, resRel, resAbs, ratio);
            //---------------------------------------------
            // GMRES(m) inner iteration starts from here
            //---------------------------------------------
            ++numIter;         // total iteration number
            count_1 = count++; // inner iteration number
            // Apply preconditioner
            tmp.SetValues(len, 0.0);
            pc->Solve(V[count_1], tmp);
            A->Apply(tmp, V[count]);
            // Modified Gram-Schmidt orthogonalization
            for (int j = 0; j < count; ++j) {
                hh[j][count_1] = V[count].Dot(V[j]);
                V[count].AXPBY(1.0, -hh[j][count_1], V[j]);
            }
            t                  = V[count].Norm2();
            hh[count][count_1] = t;
            // If t=0, we get solution subspace
            if (fabs(t) > SMALL)
                V[count].Scale(1.0 / t);
            else
                break;
            for (int j = 1; j < count; ++j) {
                t                  = hh[j - 1][count_1];
                hh[j - 1][count_1] = hsin[j - 1] * hh[j][count_1] + hcos[j - 1] * t;
                hh[j][count_1]     = -hsin[j - 1] * t + hcos[j - 1] * hh[j][count_1];
            }
            t = hh[count][count_1] * hh[count][count_1];
            t += hh[count_1][count_1] * hh[count_1][count_1];
            t = sqrt(t);
            gamma                = t > SMALL ? t : SMALL;
            hcos[count_1]        = hh[count_1][count_1] / gamma;
            hsin[count_1]        = hh[count][count_1] / gamma;
            hh[count_1][count_1] = hsin[count_1] * hh[count][count_1] +
                                   hcos[count_1] * hh[count_1][count_1];
            var[count]   = -hsin[count_1] * var[count_1];
            var[count_1] = hcos[count_1] * var[count_1];
            resAbs       = fabs(var[count]);
            ratio        = resAbs / resAbsOld;
            resRel       = resAbs / denAbs;
            resAbsOld    = resAbs;
            // Exit restart cycle if reaches tolerance
            if ((resAbs < params.absTol || resRel < params.relTol) &&
                numIter > params.minIter)
                break;
        } // end of restart cycle
        // Compute solution, first solve upper triangular system
        var[count_1] = var[count_1] / hh[count_1][count_1];
        for (int k = count - 2; k >= 0; --k) {
            t = 0.0;
            for (int j = k + 1; j < count; ++j) t -= hh[k][j] * var[j];
            t += var[k];
            var[k] = t / hh[k][k];
        }
        wk = V[count_1];
        wk.Scale(var[count_1]);
        for (int j = count - 2; j >= 0; --j) wk.AXPBY(1.0, var[j], V[j]);
        // Apply preconditioner
        tmp.SetValues(len, 0.0);
        pc->Solve(wk, tmp);
        // Update iterative solution
        x.AXPY(1.0, tmp);
        // Save the best solution so far
        if (numIter >= params.safeIter && resAbs < resAbsOld) safe = x;
        // Check whether exceeds maximal number of iterations
        if (numIter > params.maxIter) {
            errorCode = FaspRetCode::ERROR_SOLVER_MAXIT;
            break;
        }
        //---------------------------------------------
        // Prepare for the next iteration
        //---------------------------------------------
        A->Apply(x, V[0]);  // A * x -> V[0]
        V[0].XPAY(-1.0, b); // b - V[0] -> V[0]
        // Check whether converged
        resAbs = rj = V[0].Norm2();
        resRel      = resAbs / denAbs;
        if ((resRel < params.relTol || resAbs < params.absTol) &&
            numIter >= params.minIter)
            break;
        // Choose restart number adaptively
        cr = rj / ri;
        ri = rj;
        if (cr > max_cr)
            restart = maxRestart;
        else if (cr < max_cr && cr > min_cr) {
            if (restart - decrease > minRestart)
                restart -= decrease;
            else
                restart = maxRestart;
        }
    } // end of main while loop
    // If minIter == numIter == maxIter (preconditioner only), skip this
    if (not(numIter == params.minIter && numIter == params.maxIter)) {
        norm2   = V[0].Norm2();
        normInf = V[0].NormInf();
        PrintFinal(numIter, resRel, resAbs, ratio);
    }
    // Restore the saved best iteration if needed
    if (numIter > params.safeIter) x = safe;
    return errorCode;
}
References SOL::A, SOLParams::absTol, LOP::Apply(), VEC::AXPBY(), VEC::AXPY(), CLOSE_ZERO, ERROR_SOLVER_MAXIT, SOLParams::maxIter, SOLParams::minIter, SOL::norm2, SOL::normInf, SOL::numIter, SOL::params, SOL::pc, SOL::PrintFinal(), SOL::PrintHead(), SOL::PrintInfo(), SOLParams::relTol, SOLParams::safeIter, VEC::Scale(), VEC::SetValues(), SMALL, SOL::Solve(), and SUCCESS.
SetMaxMinRestart()
void GMRES::SetMaxMinRestart (const int maxRestart, const int minRestart)
Set the maximum and minmum restart numbers for variable GMRES.
Set the maximum and minimum restart.
{
    this->maxRestart = maxRestart;
    this->minRestart = minRestart;
}
Setup()
FaspRetCode GMRES::Setup (const LOP & A) override virtual
Setup the GMRES method.
Set up the GMRES method.
Reimplemented from SOL.
{
    // Set solver type
    SetSolType(SOLType::GMRES);
    len        = A.GetColSize();
    restart    = params.restart;
    maxRestart = maxRestart > params.maxIter ? params.maxIter : maxRestart;
    minRestart = minRestart > maxRestart ? maxRestart : minRestart;
    // Allocate memory for temporary vectors
    try {
        wk.SetValues(len, 0.0);
        tmp.SetValues(len, 0.0);
        safe.SetValues(len, 0.0);
        var.resize(len);
        hcos.resize(maxRestart + 1);
        hsin.resize(maxRestart);
        hh.resize(maxRestart + 1);
        for (int j = 0; j < maxRestart + 1; ++j) hh[j].resize(maxRestart);
    } catch (std::bad_alloc &ex) {
        return FaspRetCode::ERROR_ALLOC_MEM;
    }
    // Alocate memory for restart vectors
    while (maxRestart >= minRestart) {
        try {
            for (int j = 0; j < maxRestart + 1; ++j) V.push_back(safe);
            break;
        } catch (std::bad_alloc &ex) {
            maxRestart -= decrease; // reduce restart if memory is not enough
            while (!V.empty()) V.resize(0);
        }
    }
    if (maxRestart < minRestart) return FaspRetCode::ERROR_ALLOC_MEM;
    // Reset restart value according to possible range
    if (restart > maxRestart)
        restart = maxRestart;
    else if (restart < minRestart)
        restart = minRestart;
    // Setup the coefficient matrix
    this->A = &A;
    // Print used parameters
    if (params.verbose > PRINT_MIN) PrintParam(std::cout);
    return FaspRetCode::SUCCESS;
}
References SOL::A, ERROR_ALLOC_MEM, LOP::GetColSize(), GMRES, SOLParams::maxIter, SOL::params, SOLParams::restart, SOL::SetSolType(), VEC::SetValues(), and SOLParams::verbose.
The documentation for this class was generated from the following files:
GMRES.hxx
GMRES.cxx