FASP++: FaspBadAlloc Class Reference
FaspBadAlloc Class Reference
Allocation exception capturing class.
#include <RetCode.hxx>
Public Member Functions
FaspBadAlloc (const char *file_, const char *func_, const USI line_)
Default constructor.
const char * GetFile () const
return thrown file name
const char * GetFunc () const
return thrown function name
USI GetLine () const
return thrown line number
void LogExcep (std::ostream &stream=std::cout) const
Log allocation error messages in a file or to the screen.
Public Attributes
const FaspRetCode errorCode = FaspRetCode::SUCCESS
Error Code.
Detailed Description
Allocation exception capturing class.
Definition at line 94 of file RetCode.hxx.
Constructor & Destructor Documentation
FaspBadAlloc()
FaspBadAlloc::FaspBadAlloc (const char * file_, const char * func_, const USI line_) inline
Default constructor.
Definition at line 107 of file RetCode.hxx.
        : std::bad_alloc()
        , file(file_)
        , func(func_)
        , line(line_)
    {
    }
Member Function Documentation
GetFile()
const char * FaspBadAlloc::GetFile () const inline
return thrown file name
Definition at line 116 of file RetCode.hxx.
GetFunc()
const char * FaspBadAlloc::GetFunc () const inline
return thrown function name
Definition at line 117 of file RetCode.hxx.
GetLine()
USI FaspBadAlloc::GetLine () const inline
return thrown line number
Definition at line 118 of file RetCode.hxx.
LogExcep()
void FaspBadAlloc::LogExcep (std::ostream & stream = std::cout) const
Log allocation error messages in a file or to the screen.
Definition at line 94 of file RetCode.cxx.
{
    stream << "### ERROR: " << this->what() << std::endl;
    stream << "### ERROR: Check " << this->GetFile() << " in " << this->GetFunc()
           << "() at Line " << this->GetLine() << std::endl;
}
References GetFile(), GetFunc(), and GetLine().
Member Data Documentation
errorCode
const FaspRetCode FaspBadAlloc::errorCode = FaspRetCode::SUCCESS
Error Code.
Definition at line 103 of file RetCode.hxx.
The documentation for this class was generated from the following files:
RetCode.hxx
RetCode.cxx