FASP++: MATUtil.hxx File Reference
MATUtil.hxx File Reference
Tools for checking and manipulating MAT.
#include "MAT.hxx"
Macros
#define __MATUTIL_HXX__
Functions
FaspRetCode CheckMATAddSize (const MAT &mat1, const MAT &mat2)
Check whether two matrices have same sizes for addition.
FaspRetCode CheckMATMultSize (const MAT &mat1, const MAT &mat2)
Check MAT-MAT multiplication sizes.
FaspRetCode CheckMATSize (const MAT &mat, const USI &row, const USI &col)
Check whether (row,col) is out of bound.
FaspRetCode CheckMATRowSize (const MAT &mat, const USI &row)
Check whether (row,:) is out of bound.
FaspRetCode CheckMATColSize (const MAT &mat, const USI &col)
Check whether (:,col) is out of bound.
FaspRetCode CheckMATVECSize (const MAT &mat, const VEC &vec)
Check MAT-VEC multiplication sizes.
FaspRetCode CheckCSR (const USI &row, const USI &col, const USI &nnz, const std::vector< DBL > &values, const std::vector< USI > &colInd, const std::vector< USI > &rowPtr)
Check whether the data is good for CSR.
FaspRetCode CheckCSRx (const USI &row, const USI &col, const USI &nnz, const std::vector< DBL > &values, const std::vector< USI > &colInd, const std::vector< USI > &rowPtr, const std::vector< USI > &diagPtr)
Check whether the data is good for CSRx.
FaspRetCode CSRtoMAT (const USI &row, const USI &col, const USI &nnz, const std::vector< DBL > &values, const std::vector< USI > &colInd, const std::vector< USI > &rowPtr, MAT &mat)
Convert a CSR matrix to MAT (private)
FaspRetCode MTXtoMAT (const USI &row, const USI &col, const USI &nnz, const std::vector< USI > &rowInd, const std::vector< USI > &colInd, const std::vector< DBL > &values, MAT &mat)
Convert MTX data to MAT data structure.
FaspRetCode SortCSRRow (const USI &row, const USI &col, const USI &nnz, const std::vector< USI > &rowPtr, std::vector< USI > &colInd, std::vector< DBL > &values)
Sort "colInd" of each row in ascending order and rearrange "values" accordingly.
Detailed Description
Tools for checking and manipulating MAT.
Author
Chensong Zhang, Kailei Zhang
Date
Sep/26/2019
Copyright (C) 2019–present by the FASP++ team. All rights reserved.
Released under the terms of the GNU Lesser General Public License 3.0 or later.
Definition in file MATUtil.hxx.
Macro Definition Documentation
__MATUTIL_HXX__
#define __MATUTIL_HXX__
indicate MATUtil.hxx has been included before
Definition at line 13 of file MATUtil.hxx.
Function Documentation
CheckCSR()
FaspRetCode CheckCSR (const USI & row, const USI & col, const USI & nnz, const std::vector< DBL > & values, const std::vector< USI > & colInd, const std::vector< USI > & rowPtr)
Check whether the data is good for CSR.
Definition at line 110 of file MATUtil.cxx.
{
    if (row == 0 || col == 0 || nnz == 0) return FaspRetCode ::SUCCESS;
    if (row != rowPtr.size() - 1) {
        std::cout << "### ERROR: row= " << row << ", but rowPtr.size= " << rowPtr.size()
                  << std::endl;
        goto WRONG_CSR;
    }
    if (row <= 0 || col <= 0) {
        std::cout << "### ERROR: row= " << row << ", col= " << col << std::endl;
        goto WRONG_CSR;
    }
    if (nnz != colInd.size()) {
        std::cout << "### ERROR: nnz= " << nnz << ", but colInd.size= " << colInd.size()
                  << std::endl;
        goto WRONG_CSR;
    }
    if (nnz != values.size()) {
        std::cout << "### ERROR: nnz= " << nnz << ", but values.size= " << values.size()
                  << std::endl;
        goto WRONG_CSR;
    }
    if (nnz != rowPtr[row] - rowPtr[0]) {
        std::cout << "### ERROR: nnz= " << nnz
                  << ", rowPtr[last]-rowPtr[first]= " << rowPtr[row] - rowPtr[0]
                  << std::endl;
        goto WRONG_CSR;
    }
    for (USI j = 0; j < row; ++j) {
        if (rowPtr[j] > rowPtr[j + 1]) {
            std::cout << "### ERROR: Problem in " << j << "-th row, "
                      << "starting row pointer = " << rowPtr[j]
                      << ", ending row pointer = " << rowPtr[j + 1] << std::endl;
            goto WRONG_CSR;
        }
    }
    USI begin, end;
    for (USI j = 0; j < row; ++j) {
        begin = rowPtr[j];
        end   = rowPtr[j + 1];
        if (begin == end) continue;
        for (USI k = begin; k < end; ++k) {
            if (0 > colInd[k] || colInd[k] >= col) {
                std::cout << "### ERROR: Wrong column indices" << std::endl;
                goto WRONG_CSR;
            }
        }
    }
    return FaspRetCode::SUCCESS;
WRONG_CSR:
    return FaspRetCode::ERROR_MAT_DATA;
}
References ERROR_MAT_DATA, and SUCCESS.
CheckCSRx()
FaspRetCode CheckCSRx (const USI & row, const USI & col, const USI & nnz, const std::vector< DBL > & values, const std::vector< USI > & colInd, const std::vector< USI > & rowPtr, const std::vector< USI > & diagPtr)
Check whether the data is good for CSRx.
basic examinations
simple examinations
exam diagPtr and colInd
Definition at line 177 of file MATUtil.cxx.
{
    if (row == 0 || col == 0 || nnz == 0) return FaspRetCode::SUCCESS;
    /*
     * some simple examinations about parameters
     * to judge whether they are CSRx' parameters
     */
    /*----------------  begin  ----------------*/
    USI count = 0;
    USI begin, end;
    if (row != rowPtr.size() - 1) goto Return;
    if (row <= 0 || col <= 0) goto Return;
    if (((row > col) ? col : row) != diagPtr.size()) goto Return;
    if (nnz != colInd.size()) goto Return;
    if (nnz != values.size()) goto Return;
    if (nnz != rowPtr[rowPtr.size() - 1]) goto Return;
    for (USI j = 0; j < row; ++j) {
        if (rowPtr[j] >= rowPtr[j + 1]) goto Return;
    }
    if (rowPtr[0] < 0 || rowPtr[row] > nnz) goto Return;
    for (USI j = 0; j < row; ++j) {
        begin = rowPtr[j];
        end   = rowPtr[j + 1];
        if (begin == end) goto Return;
        if (end == begin + 1) {
            if (colInd[begin] != j) goto Return;
        }
        if (end > begin + 1) {
            for (USI k = begin; k < end - 1; ++k) {
                if (colInd[k] >= colInd[k + 1]) goto Return;
            }
            if (0 > colInd[begin]) goto Return;
            if (colInd[end - 1] >= col) goto Return;
        }
    }
    for (USI j = 0; j < row; ++j) {
        begin = rowPtr[j];
        end   = rowPtr[j + 1];
        for (USI k = begin; k < end; ++k) {
            if (colInd[k] == j) {
                if (diagPtr[count] != k)
                    goto Return;
                else
                    ++count;
            }
        }
    }
    if (count != diagPtr.size()) goto Return;
    return FaspRetCode::SUCCESS;
Return:
    return FaspRetCode::ERROR_INPUT_PAR;
}
References ERROR_INPUT_PAR, and SUCCESS.
CheckMATAddSize()
FaspRetCode CheckMATAddSize (const MAT & mat1, const MAT & mat2)
Check whether two matrices have same sizes for addition.
Definition at line 17 of file MATUtil.cxx.
{
    try {
        if (mat1.GetRowSize() != mat2.GetRowSize() ||
            mat2.GetColSize() != mat2.GetColSize() || mat1.GetRowSize() <= 0 ||
            mat1.GetColSize() <= 0) {
            auto errorCode = FaspRetCode::ERROR_NONMATCH_SIZE;
            throw(FaspRunTime(errorCode, __FILE__, __FUNCTION__, __LINE__));
        }
    } catch (FaspRunTime& ex) {
        ex.LogExcep();
        return ex.errorCode;
    }
    return FaspRetCode::SUCCESS;
}
References ERROR_NONMATCH_SIZE, FaspRunTime::errorCode, LOP::GetColSize(), LOP::GetRowSize(), FaspRunTime::LogExcep(), and SUCCESS.
CheckMATColSize()
FaspRetCode CheckMATColSize (const MAT & mat, const USI & col)
Check whether (:,col) is out of bound.
Definition at line 80 of file MATUtil.cxx.
{
    try {
        if (col < 0 || col >= mat.GetColSize()) {
            auto errorCode = FaspRetCode::ERROR_MAT_SIZE;
            throw(FaspRunTime(errorCode, __FILE__, __FUNCTION__, __LINE__));
        }
    } catch (FaspRunTime& ex) {
        ex.LogExcep();
        return ex.errorCode;
    }
    return FaspRetCode::SUCCESS;
}
References ERROR_MAT_SIZE, FaspRunTime::errorCode, LOP::GetColSize(), FaspRunTime::LogExcep(), and SUCCESS.
CheckMATMultSize()
FaspRetCode CheckMATMultSize (const MAT & mat1, const MAT & mat2)
Check MAT-MAT multiplication sizes.
Definition at line 34 of file MATUtil.cxx.
{
    try {
        if (mat1.GetColSize() != mat2.GetRowSize() || mat1.GetColSize() <= 0 ||
            mat2.GetRowSize() <= 0) {
            auto errorCode = FaspRetCode::ERROR_NONMATCH_SIZE;
            throw(FaspRunTime(errorCode, __FILE__, __FUNCTION__, __LINE__));
        }
    } catch (FaspRunTime& ex) {
        ex.LogExcep();
        return ex.errorCode;
    }
    return FaspRetCode::SUCCESS;
}
References ERROR_NONMATCH_SIZE, FaspRunTime::errorCode, LOP::GetColSize(), LOP::GetRowSize(), FaspRunTime::LogExcep(), and SUCCESS.
CheckMATRowSize()
FaspRetCode CheckMATRowSize (const MAT & mat, const USI & row)
Check whether (row,:) is out of bound.
Definition at line 65 of file MATUtil.cxx.
{
    try {
        if (row < 0 || row >= mat.GetRowSize()) {
            auto errorCode = FaspRetCode::ERROR_MAT_SIZE;
            throw(FaspRunTime(errorCode, __FILE__, __FUNCTION__, __LINE__));
        }
    } catch (FaspRunTime& ex) {
        ex.LogExcep();
        return ex.errorCode;
    }
    return FaspRetCode::SUCCESS;
}
References ERROR_MAT_SIZE, FaspRunTime::errorCode, LOP::GetRowSize(), FaspRunTime::LogExcep(), and SUCCESS.
CheckMATSize()
FaspRetCode CheckMATSize (const MAT & mat, const USI & row, const USI & col)
Check whether (row,col) is out of bound.
Definition at line 50 of file MATUtil.cxx.
{
    try {
        if (row < 0 || row >= mat.GetRowSize() || col < 0 || col >= mat.GetColSize()) {
            auto errorCode = FaspRetCode::ERROR_MAT_SIZE;
            throw(FaspRunTime(errorCode, __FILE__, __FUNCTION__, __LINE__));
        }
    } catch (FaspRunTime& ex) {
        ex.LogExcep();
        return ex.errorCode;
    }
    return FaspRetCode::SUCCESS;
}
References ERROR_MAT_SIZE, FaspRunTime::errorCode, LOP::GetColSize(), LOP::GetRowSize(), FaspRunTime::LogExcep(), and SUCCESS.
CheckMATVECSize()
FaspRetCode CheckMATVECSize (const MAT & mat, const VEC & vec)
Check MAT-VEC multiplication sizes.
Definition at line 95 of file MATUtil.cxx.
{
    try {
        if (mat.GetColSize() != vec.GetSize()) {
            auto errorCode = FaspRetCode::ERROR_NONMATCH_SIZE;
            throw(FaspRunTime(errorCode, __FILE__, __FUNCTION__, __LINE__));
        }
    } catch (FaspRunTime& ex) {
        ex.LogExcep();
        return ex.errorCode;
    }
    return FaspRetCode::SUCCESS;
}
References ERROR_NONMATCH_SIZE, FaspRunTime::errorCode, LOP::GetColSize(), VEC::GetSize(), FaspRunTime::LogExcep(), and SUCCESS.
CSRtoMAT()
FaspRetCode CSRtoMAT (const USI & row, const USI & col, const USI & nnz, const std::vector< DBL > & values, const std::vector< USI > & colInd, const std::vector< USI > & rowPtr, MAT & mat)
Convert a CSR matrix to MAT (private)
Definition at line 303 of file MATUtil.cxx.
{
    FaspRetCode       retCode;
    USI               begin, end, numZeroDiag = 0;
    std::vector<bool> isZeroDiag(row);
    for (USI i = 0; i < row; ++i) {
        isZeroDiag[i] = false; // Set a marker for diagonal pointer
        begin         = rowPtr[i];
        end           = rowPtr[i + 1];
        for (USI k = begin; k < end; ++k) {
            if (colInd[k] == i) {
                isZeroDiag[i] = true; // Diagonal entry found
                break;
            }
        }
        if (!isZeroDiag[i]) ++numZeroDiag; // If no diagonal entry, insert a zero
    }
    if (numZeroDiag == 0) {
        // Set values for MAT matrix
        try {
            retCode = CheckCSR(row, col, nnz, values, colInd, rowPtr);
            if (retCode < 0)
                throw(FaspRunTime(retCode, __FILE__, __FUNCTION__, __LINE__));
            else
                mat.SetValues(row, col, nnz, values, colInd, rowPtr);
        } catch (FaspRunTime& ex) {
            ex.LogExcep();
            return ex.errorCode;
        }
    }
    // Add a spot for each zero diagonal entry
    USI nnzNew = nnz + numZeroDiag, count = 0;
    USI nextEntry, diagZeroAdded          = 0;
    std::vector<USI> colIndNew;
    std::vector<DBL> valuesNew;
    std::vector<USI> rowPtrNew;
    try {
        colIndNew.resize(nnzNew);
        valuesNew.resize(nnzNew);
        rowPtrNew.resize(row + 1);
    } catch (std::bad_alloc& ex) {
        throw(FaspBadAlloc(__FILE__, __FUNCTION__, __LINE__));
    }
    rowPtrNew[0] = 0; // Starting index always 0
    for (USI m = 0; m < row + 1; ++m) rowPtrNew[m] = 0;
    USI k, j;
    for (USI i = 0; i < row; ++i) {
        begin = rowPtr[i];
        end   = rowPtr[i + 1];
        if (!isZeroDiag[i]) { // No diagonal entry
            // Lower triangular part
            nextEntry = begin;
            for (k = begin; k < end; ++k) {
                if (colInd[k] < i) {
                    valuesNew[count] = values[k];
                    colIndNew[count] = colInd[k];
                    ++count;
                } else {
                    nextEntry = k; // Record next nonzero location
                    break;
                }
            }
            // Zero diagonal part
            valuesNew[count] = 0.0;
            colIndNew[count] = i;
            ++count;
            if (colInd[end - 1] < i) nextEntry = end;
            // Upper triangular part
            for (j = nextEntry; j < end; ++j) {
                valuesNew[count] = values[j];
                colIndNew[count] = colInd[j];
                ++count;
            }
            // Update row pointers
            ++diagZeroAdded;
        } else { // With diagonal entry, just copy
            for (k = begin; k < end; ++k) {
                valuesNew[count] = values[k];
                colIndNew[count] = colInd[k];
                ++count;
            }
        }
        rowPtrNew[i + 1] = rowPtr[i + 1] + diagZeroAdded;
    }
    // Set values for MAT matrix
    try {
        retCode = CheckCSR(row, col, nnzNew, valuesNew, colIndNew, rowPtrNew);
        if (retCode < 0)
            throw(FaspRunTime(retCode, __FILE__, __FUNCTION__, __LINE__));
        else
            mat.SetValues(row, col, nnzNew, valuesNew, colIndNew, rowPtrNew);
    } catch (FaspRunTime& ex) {
        ex.LogExcep();
        return ex.errorCode;
    }
    return retCode;
}
References CheckCSR(), FaspRunTime::errorCode, FaspRunTime::LogExcep(), and MAT::SetValues().
MTXtoMAT()
FaspRetCode MTXtoMAT (const USI & row, const USI & col, const USI & nnz, const std::vector< USI > & rowInd, const std::vector< USI > & colInd, const std::vector< DBL > & values, MAT & mat)
Convert MTX data to MAT data structure.
Convert MTX data to MAT data structure.
Definition at line 416 of file MATUtil.cxx.
{
    auto retCode = FaspRetCode::SUCCESS;
    std::vector<USI> rowPtrCSR;
    std::vector<USI> colIndCSR;
    std::vector<DBL> valuesCSR;
    // Convert data format from MTX to CSR
    MTXtoCSR(row, col, nnz, rowInd, colInd, values, valuesCSR, colIndCSR, rowPtrCSR);
    // Sort CSR matrix row by row
    SortCSRRow(row, col, nnz, rowPtrCSR, colIndCSR, valuesCSR);
    // Check whether diagonal is a nonzero position
    CSRtoMAT(row, col, nnz, valuesCSR, colIndCSR, rowPtrCSR, mat);
    return retCode;
}
References SUCCESS.
SortCSRRow()
FaspRetCode SortCSRRow (const USI & row, const USI & col, const USI & nnz, const std::vector< USI > & rowPtr, std::vector< USI > & colInd, std::vector< DBL > & values)
Sort "colInd" of each row in ascending order and rearrange "values" accordingly.
Definition at line 439 of file MATUtil.cxx.
{
    FaspRetCode retCode;
    USI         l, begin, end, index;
    DBL         data;
    for (USI j = 0; j < row; ++j) {
        begin = rowPtr[j];
        end   = rowPtr[j + 1];
        if (end <= begin + 1) continue;
        for (USI k = begin + 1; k < end; ++k) {
            index = colInd[k];
            data  = values[k];
            for (l = k - 1; l >= begin; --l) {
                if (index < colInd[l]) {
                    colInd[l + 1] = colInd[l];
                    values[l + 1] = values[l];
                } else {
                    break;
                }
            }
            colInd[l + 1] = index;
            values[l + 1] = data;
        }
    }
    try {
        retCode = CheckCSR(row, col, nnz, values, colInd, rowPtr);
        if (retCode < 0) throw(FaspRunTime(retCode, __FILE__, __FUNCTION__, __LINE__));
    } catch (FaspRunTime& ex) {
        ex.LogExcep();
        return ex.errorCode;
    }
    return retCode;
}
References CheckCSR(), FaspRunTime::errorCode, and FaspRunTime::LogExcep().