FASP++: VECUtil.cxx File Reference
VECUtil.cxx File Reference
Some auxiliary functions for VEC.
#include <cmath>
#include "VECUtil.hxx"
Functions
FaspRetCode CheckVECSize (const VEC &v)
Check whether the size of VEC object is zero.
FaspRetCode CheckVECSize (const VEC &v1, const VEC &v2)
Check whether two VEC sizes match.
FaspRetCode CheckVECSize (const VEC &v, const INT &position)
Check whether vector crossover.
FaspRetCode CheckVECZero (const VEC &v, const DBL tol)
Check whether there is a zero entry in VEC object.
Detailed Description
Some auxiliary functions for VEC.
Author
Kailei Zhang
Date
Sep/25/2019
Copyright (C) 2019–present by the FASP++ team. All rights reserved.
Released under the terms of the GNU Lesser General Public License 3.0 or later.
Definition in file VECUtil.cxx.
Function Documentation
CheckVECSize() [1/3]
FaspRetCode CheckVECSize (const VEC & v)
Check whether the size of VEC object is zero.
Definition at line 19 of file VECUtil.cxx.
{
    FaspRetCode retCode = FaspRetCode::SUCCESS; // Return success if no-throw
    try {
        if (v.GetSize() == 0) {
            retCode = FaspRetCode::ERROR_VEC_SIZE;
            throw(FaspRunTime(retCode, __FILE__, __FUNCTION__, __LINE__));
        }
    } catch (FaspRunTime &ex) {
        ex.LogExcep();
        return ex.errorCode;
    }
    return retCode;
}
References ERROR_VEC_SIZE, FaspRunTime::errorCode, VEC::GetSize(), FaspRunTime::LogExcep(), and SUCCESS.
CheckVECSize() [2/3]
FaspRetCode CheckVECSize (const VEC & v, const INT & position)
Check whether vector crossover.
Definition at line 49 of file VECUtil.cxx.
{
    FaspRetCode retCode = FaspRetCode::SUCCESS; // Return success if no-throw
    try {
        if (position >= v.GetSize() || position < 0) {
            retCode = FaspRetCode::ERROR_VEC_SIZE;
            throw(FaspRunTime(retCode, __FILE__, __FUNCTION__, __LINE__));
        }
    } catch (FaspRunTime &ex) {
        ex.LogExcep();
        return ex.errorCode;
    }
    return retCode;
}
References ERROR_VEC_SIZE, FaspRunTime::errorCode, VEC::GetSize(), FaspRunTime::LogExcep(), and SUCCESS.
CheckVECSize() [3/3]
FaspRetCode CheckVECSize (const VEC & v1, const VEC & v2)
Check whether two VEC sizes match.
Definition at line 34 of file VECUtil.cxx.
{
    FaspRetCode retCode = FaspRetCode::SUCCESS; // Return success if no-throw
    try {
        if (v1.GetSize() != v2.GetSize()) {
            retCode = FaspRetCode::ERROR_NONMATCH_SIZE;
            throw(FaspRunTime(retCode, __FILE__, __FUNCTION__, __LINE__));
        }
    } catch (FaspRunTime &ex) {
        ex.LogExcep();
        return ex.errorCode;
    }
    return retCode;
}
References ERROR_NONMATCH_SIZE, FaspRunTime::errorCode, VEC::GetSize(), FaspRunTime::LogExcep(), and SUCCESS.
CheckVECZero()
FaspRetCode CheckVECZero (const VEC & v, const DBL tol)
Check whether there is a zero entry in VEC object.
Definition at line 64 of file VECUtil.cxx.
{
    FaspRetCode retCode = FaspRetCode::SUCCESS; // Return success if no-throw
    for (INT j = 0; j < v.GetSize(); ++j) {
        try {
            if (fabs(v[j]) <= tol) {
                retCode = FaspRetCode::ERROR_DIVIDE_ZERO;
                throw(FaspRunTime(retCode, __FILE__, __FUNCTION__, __LINE__));
            }
        } catch (FaspRunTime &ex) {
            ex.LogExcep();
            return ex.errorCode;
        }
    }
    return retCode;
}
References ERROR_DIVIDE_ZERO, FaspRunTime::errorCode, VEC::GetSize(), FaspRunTime::LogExcep(), and SUCCESS.