name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: mkdir cmake_debug
    - name: cmake
      run: cd cmake_debug && cmake ..
    - name: make
      run: cd cmake_debug && make
